# IBM Coursera Applied Data Science 
# Capstone Project - The Battle of Neighborhoods (Week 2)

## Table of contents

* [Introduction: Business Problem](#introduction)
* [Data](#data)
* [Methodology](#methodology)
* [Analysis](#analysis)
* [Results and Discussion](#results)
* [Conclusion](#conclusion)


## Introduction: Business Problem <a name="introduction"></a>

The problem this project aims to tackle is the search for a new neighborhood in case people have to move to a foreign city.
To be more specific, this project serves to help people who have to move to a foreign city to find a new neighbourhood that is as similar as possible to the old neighbourhood they have to leave. On top of that, this project tries to identify the most suitable neighborhood for a given set of preferences.

Due to very different reasons a lot of people have to move homes. The decision process of where to buy a new house or rent an appartement is quite complex. A lot of features have to be taken into consideration, e.g. socio economic factors like unemployment or the income level of the neighborhood, but also crime rates, housing prices, reputation of public schools for the children, shops, malls, theatres, hospitals et cetera.   

## Data <a name="data"></a>

To complete this assignment I will be using the Foursquare API for location data as well as other datasets for socioeconomic criterias, as well as crime data and housing data. For practical purposes, I will rely on data that is available on the city of Chicago's Data Portal and housing prices from a large real estate agent:

1. <a href="https://de.foursquare.com/explore?mode=url&near=Chicago%2C%20IL%2C%20USA&nearGeoId=72057594042815334">Foursquare location data</a>
1. <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2">Socioeconomic Indicators in Chicago</a>
1. <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2">Chicago Crime Data</a>
1. <a href="https://www.zillow.com/research/data/">Home values - Zillow Home Value Index (ZHVI)</a>




### Data Description:  


__1. Foursquare API__

As requested by the assignment, this project will heavily use Four-square API as its prime data gathering source. With the API I will perform location search, location sharing and details about a business. Due to limitations of the API requests possible, the number of places per neighborhood parameter would reasonably be set to 100 and the radius parameter would be set to 500.

To find similarities between neighborhoods in New York and Chicago, we need to gather data about different kind of  venues to find the characteristics. Hence, I will use Foursquare data for this task. 

To determine the similarities of both cities, I will segment and cluster the neighborhoods to find similar places. In order to do that, a k-means clustering algorithm will be utilized, basen on location data provided by the Foursquare API.


__2. Selected Socioeconomic Indicators in Chicago__

The city of Chicago released a dataset of socioeconomic data to the Chicago City Portal.



A detailed description of the dataset can be found on [the city of Chicago's website](
https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2), but to summarize, the dataset has the following variables:

* **Community Area Number** (`ca`): Used to uniquely identify each row of the dataset

* **Community Area Name** (`community_area_name`): The name of the region in the city of Chicago 

* **Percent of Housing Crowded** (`percent_of_housing_crowded`): Percent of occupied housing units with more than one person per room

* **Percent Households Below Poverty** (`percent_households_below_poverty`): Percent of households living below the federal poverty line

* **Percent Aged 16+ Unemployed** (`percent_aged_16_unemployed`): Percent of persons over the age of 16 years that are unemployed

* **Percent Aged 25+ without High School Diploma** (`percent_aged_25_without_high_school_diploma`): Percent of persons over the age of 25 years without a high school education

* **Percent Aged Under** 18 or Over 64:Percent of population under 18 or over 64 years of age (`percent_aged_under_18_or_over_64`): (ie. dependents)

* **Per Capita Income** (`per_capita_income_`): Community Area per capita income is estimated as the sum of tract-level aggragate incomes divided by the total population

* **Hardship Index** (`hardship_index`): Score that incorporates each of the six selected socioeconomic indicators

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012. Scores on the hardship index can range from 1 to 100, with a higher index number representing a greater level of hardship. I will use the Hardship Index only as this score includes each of the indicators.

I acknowledge that the time series ends in the year of 2012, but for this assignment I will ignore this fact and assume that the data is up to date and still valid for this decision process.


__3. Chicago Crime Data__  

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days. 

This dataset is quite large - over 1.5GB in size with over 7 million rows. A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2



__4. Home values - Zillow Home Value Index (ZHVI)__  

The Zillow Home Value Index (ZHVI)is a smoothed, seasonally adjusted measure of the typical home value and market changes across a given region and housing type. 

Zillow publishes top-tier ZHVI (USD, typical value for homes within the 65th to 95th percentile range for a given region) and bottom-tier ZHVI (USD, typical value for homes that fall within the 5th to 35th percentile range for a given region). 

Zillow also publishes ZHVI for all single-family residences (USD, typical value for all single-family homes in a given region), for condo/coops (USD), for all homes with 1, 2, 3, 4 and 5+ bedrooms (USD), and the ZHVI per square foot (USD, typical value of all homes per square foot calculated by taking the estimated home value for each home in a given region and dividing it by the home’s square footage). 

Check out https://www.zillow.com/research/data/ for an overview of ZHVI and a deep-dive into its methodology.


## Methodology <a name="methodology"></a>

The methodolgy of this project can be described by the following steps:

__A: Define the characteristics of the neighborhoods__
1. Retrieve the names of neighborhoods for both cities, we will label the current residence as "old" city or neighborhood and the new destination as "new" city or neighborhood.
2. Put the names of the neighborhoods in a dataframe and add the latitude and longitude data.
3. Use the Foursquare API to get location data of the venues in all the neighborhoods.
4. Clustering of the neighborhoods with a clustering algorithm to find similar neighborhoods in both cities.
5. Define each cluster by checking the main characteristics based on venues data.
6. Pick the cluster that your old neighborhood is in and select the neighborhoods from the new city.

__B: Scoring of neighborhoods within the new city to make a recommendation of the best places__
7. Score each of the potential new neighborhood based on socioeconomic data and define the top 10 list.
8. Score remaining neighborhood based on crime data and we'll get the top 5 list.
9. Last step is to check housing prices for the top 3 list and decide based on financial resources available.



## Analysis <a name="analysis"></a>

In [259]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import json # library to handle JSON files

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

import folium # map rendering library

import geopandas
import geopy

print('Libraries imported.')

Libraries imported.


### A: Define the characteristics of the neighborhoods

#### 1. Retrieve the names of neighborhoods for both cities, we will label the current residence as "old" city or neighborhood and the new destination as "new" city or neighborhood.


#### 2. Put the names of the neighborhoods in a dataframe and add the latitude and longitude data.




As an example for this project, I will be using following two cities:

__New York__ is set to be the "old" home and serves as a starting point for the analysis

__Chicago__ will be the "new" home and we will dive into a lot of data to find the best fit

In [260]:
old_city = ('New York')
old_borough = ('Manhattan')
new_city = ('Chicago')
print("The old city is set to be " + old_city + ", and the new one is " + new_city)

The old city is set to be New York, and the new one is Chicago


Let's start with the old city!

__Old City Data__

First task is to find a data source that satisfies our need, i.e. contains at least the neighborhood names. In this case the JSON file includes the latitude and longitude values as well.


In [261]:
import json
json_data = open("nyu-2451-34572-geojson.json")
ny_data = json.load(json_data)

In [262]:
# let's have a look at the data
ny_data

{'type': 'FeatureCollection',
 'totalFeatures': 306,
 'features': [{'type': 'Feature',
   'id': 'nyu_2451_34572.1',
   'geometry': {'type': 'Point',
    'coordinates': [-73.84720052054902, 40.89470517661]},
   'geometry_name': 'geom',
   'properties': {'name': 'Wakefield',
    'stacked': 1,
    'annoline1': 'Wakefield',
    'annoline2': None,
    'annoline3': None,
    'annoangle': 0.0,
    'borough': 'Bronx',
    'bbox': [-73.84720052054902,
     40.89470517661,
     -73.84720052054902,
     40.89470517661]}},
  {'type': 'Feature',
   'id': 'nyu_2451_34572.2',
   'geometry': {'type': 'Point',
    'coordinates': [-73.82993910812398, 40.87429419303012]},
   'geometry_name': 'geom',
   'properties': {'name': 'Co-op City',
    'stacked': 2,
    'annoline1': 'Co-op',
    'annoline2': 'City',
    'annoline3': None,
    'annoangle': 0.0,
    'borough': 'Bronx',
    'bbox': [-73.82993910812398,
     40.87429419303012,
     -73.82993910812398,
     40.87429419303012]}},
  {'type': 'Feature',
 

Notice how all the relevant data is in the features key, which is basically a list of the neighborhoods. So, let's define a new variable that includes this data.

In [263]:
old_neigh_data = ny_data['features']

In [264]:
# Tranform the data into a pandas dataframe

# define the dataframe columns
column_names = ['Borough', 'Neighborhood', 'Latitude', 'Longitude'] 

# instantiate the dataframe
old_neigh_df = pd.DataFrame(columns=column_names)

# loop through the data and fill the dataframe one row at a time.
for data in old_neigh_data:
    
    old_borough = old_neigh_name = data['properties']['borough'] 
    old_neigh_name = data['properties']['name']
    
    old_neigh_latlon = data['geometry']['coordinates']
    old_neigh_lat = old_neigh_latlon[1]
    old_neigh_lon = old_neigh_latlon[0]
    
    old_neigh_df = old_neigh_df.append({'Borough': old_borough,
                                        'Neighborhood': old_neigh_name,
                                        'Latitude': old_neigh_lat,
                                        'Longitude': old_neigh_lon}, ignore_index=True)

In [265]:
# quick check
old_neigh_df.head()

Borough Neighborhood   Latitude  Longitude
0   Bronx    Wakefield  40.894705 -73.847201
1   Bronx   Co-op City  40.874294 -73.829939
2   Bronx  Eastchester  40.887556 -73.827806
3   Bronx    Fieldston  40.895437 -73.905643
4   Bronx    Riverdale  40.890834 -73.912585

Limit to one borough for better performance and avoid running into Foursquare API daily call quota limits.

In [266]:
old_neigh_df = old_neigh_df[old_neigh_df['Borough'] == 'Manhattan'].reset_index(drop=True)
print(old_neigh_df.shape)
old_neigh_df.head()

(40, 4)


Borough        Neighborhood   Latitude  Longitude
0  Manhattan         Marble Hill  40.876551 -73.910660
1  Manhattan           Chinatown  40.715618 -73.994279
2  Manhattan  Washington Heights  40.851903 -73.936900
3  Manhattan              Inwood  40.867684 -73.921210
4  Manhattan    Hamilton Heights  40.823604 -73.949688

There are 40 distinct neighborhoods in Manhattan.

Use geopy library to get the latitude and longitude values

In [267]:
old_address = 'Manhattan, NY'

geolocator = Nominatim(user_agent="old_city_explorer")
location = geolocator.geocode(old_address)
old_latitude = location.latitude
old_longitude = location.longitude
print('The geograpical coordinate of ' + old_address + ' are {}, {}.'.format(old_latitude, old_longitude))

The geograpical coordinate of Manhattan, NY are 40.7896239, -73.9598939.


In [268]:
# create map of New York using latitude and longitude values
map_old_city = folium.Map(location=[old_latitude, old_longitude], zoom_start=11)

# add markers to map
for lat, lng, borough, neighborhood in zip(old_neigh_df['Latitude'], old_neigh_df['Longitude'], old_neigh_df['Borough'], old_neigh_df['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_old_city)  
    
map_old_city

__New City Data__

Let's repeat the same process for the new city. For this purpose I reference to the data set that can be found on the website of the City of Chicago. It also contains socioeconomic metrics that I will use at a later stage in this project.

In [269]:
# we can find the names of the neighborhoods in this data source
new_socioeconomic_data = pd.read_csv('https://data.cityofchicago.org/resource/jcxq-k9xf.csv')
new_socioeconomic_data.shape

(78, 9)

In [270]:
# quick check
new_socioeconomic_data.head()

ca community_area_name  percent_of_housing_crowded  \
0  1.0         Rogers Park                         7.7   
1  2.0          West Ridge                         7.8   
2  3.0              Uptown                         3.8   
3  4.0      Lincoln Square                         3.4   
4  5.0        North Center                         0.3   

   percent_households_below_poverty  percent_aged_16_unemployed  \
0                              23.6                         8.7   
1                              17.2                         8.8   
2                              24.0                         8.9   
3                              10.9                         8.2   
4                               7.5                         5.2   

   percent_aged_25_without_high_school_diploma  \
0                                         18.2   
1                                         20.8   
2                                         11.8   
3                                         13.4   
4                                          4.5   

   percent_aged_under_18_or_over_64  per_capita_income_  hardship_index  
0                              27.5               23939            39.0  
1                              38.5               23040            46.0  
2                              22.2               35787            20.0  
3                              25.5               37524            17.0  
4                              26.2               57123             6.0

In [271]:
# change column names to match the names given in the assignment
new_socioeconomic_data.columns = ['Community Area Number',
                 'Neighborhood',
                 'PERCENT OF HOUSING CROWDED',
                 'PERCENT HOUSEHOLDS BELOW POVERTY',
                 'PERCENT AGED 16+ UNEMPLOYED',
                 'PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA',
                 'PERCENT AGED UNDER 18 OR OVER 64',
                 'PER CAPITA INCOME',
                 'Hardship Index'
                ] 

new_socioeconomic_data.head()

Community Area Number    Neighborhood  PERCENT OF HOUSING CROWDED  \
0                    1.0     Rogers Park                         7.7   
1                    2.0      West Ridge                         7.8   
2                    3.0          Uptown                         3.8   
3                    4.0  Lincoln Square                         3.4   
4                    5.0    North Center                         0.3   

   PERCENT HOUSEHOLDS BELOW POVERTY  PERCENT AGED 16+ UNEMPLOYED  \
0                              23.6                          8.7   
1                              17.2                          8.8   
2                              24.0                          8.9   
3                              10.9                          8.2   
4                               7.5                          5.2   

   PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA  \
0                                          18.2   
1                                          20.8   
2                                          11.8   
3                                          13.4   
4                                           4.5   

   PERCENT AGED UNDER 18 OR OVER 64  PER CAPITA INCOME  Hardship Index  
0                              27.5              23939            39.0  
1                              38.5              23040            46.0  
2                              22.2              35787            20.0  
3                              25.5              37524            17.0  
4                              26.2              57123             6.0

In [272]:
# let's focus on community number and neighorhood name in the first place
new_neigh_df = new_socioeconomic_data[['Community Area Number', 'Neighborhood']].reset_index(drop=True)
new_neigh_df.head()

Community Area Number    Neighborhood
0                    1.0     Rogers Park
1                    2.0      West Ridge
2                    3.0          Uptown
3                    4.0  Lincoln Square
4                    5.0    North Center

In [273]:
print(new_neigh_df.shape)

(78, 2)


There are 75 distinct neighborhoods in Chicago.

__Geocoding__

Geocoding is the computational process of transforming a physical address description to a location on the Earth’s surface (spatial representation in numerical coordinates).

We use Nominatim Geocoding service, which is built on top of OpenStreetMap data. We create locator that holds the Geocoding service, Nominatim. Then we pass the locator we created to geocode any address.

We delay our Geocoding 1 second between each address. This is convenient when you are Geocoding a large number of physical addresses as the Geocoding service provider can deny access to the service.

In [274]:
# add another column with the city name and additional information for geocoding
new_neigh_df['ADDRESS'] = new_neigh_df['Neighborhood'] + ', Chicago, IL, USA'
new_neigh_df.head()

Community Area Number    Neighborhood                           ADDRESS
0                    1.0     Rogers Park     Rogers Park, Chicago, IL, USA
1                    2.0      West Ridge      West Ridge, Chicago, IL, USA
2                    3.0          Uptown          Uptown, Chicago, IL, USA
3                    4.0  Lincoln Square  Lincoln Square, Chicago, IL, USA
4                    5.0    North Center    North Center, Chicago, IL, USA

In [275]:
geolocator = Nominatim(user_agent="foursquare_agent")

from geopy.extra.rate_limiter import RateLimiter

# Function to delay between geocoding calls
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

# Create location column
new_neigh_df['location'] = new_neigh_df['ADDRESS'].apply(geocode)

# Create longitude, laatitude and altitude from location column (returns tuple)
new_neigh_df['point'] = new_neigh_df['location'].apply(lambda loc: tuple(loc.point) if loc else None)

# Split point column into latitude, longitude and altitude columns
new_neigh_df[['Latitude', 'Longitude', 'Altitude']] = pd.DataFrame(new_neigh_df['point'].tolist(), index=new_neigh_df.index)

new_neigh_df.head()

Community Area Number    Neighborhood                           ADDRESS  \
0                    1.0     Rogers Park     Rogers Park, Chicago, IL, USA   
1                    2.0      West Ridge      West Ridge, Chicago, IL, USA   
2                    3.0          Uptown          Uptown, Chicago, IL, USA   
3                    4.0  Lincoln Square  Lincoln Square, Chicago, IL, USA   
4                    5.0    North Center    North Center, Chicago, IL, USA   

                                            location  \
0  (Rogers Park, Chicago, Cook County, Illinois, ...   
1  (West Ridge, Chicago, Cook County, Illinois, 6...   
2  (Uptown, Chicago, Cook County, Illinois, 60640...   
3  (Lincoln Square, Chicago, Cook County, Illinoi...   
4  (North Center, Chicago, Cook County, Illinois,...   

                                          point   Latitude  Longitude  \
0        (42.01053135, -87.67074819664808, 0.0)  42.010531 -87.670748   
1                (42.0035482, -87.6962426, 0.0)  42.003548 -87.696243   
2                (41.9666299, -87.6555458, 0.0)  41.966630 -87.655546   
3  (41.975989850000005, -87.6896163305115, 0.0)  41.975990 -87.689616   
4                (41.9561073, -87.6791596, 0.0)  41.956107 -87.679160   

   Altitude  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0

In [276]:
# drop all columns that are irrelevant
new_neigh_df = new_neigh_df.drop(['ADDRESS', 'location', 'point', 'Altitude'], axis=1)
new_neigh_df

Community Area Number            Neighborhood   Latitude  Longitude
0                     1.0             Rogers Park  42.010531 -87.670748
1                     2.0              West Ridge  42.003548 -87.696243
2                     3.0                  Uptown  41.966630 -87.655546
3                     4.0          Lincoln Square  41.975990 -87.689616
4                     5.0            North Center  41.956107 -87.679160
5                     6.0               Lake View  41.947050 -87.655429
6                     7.0            Lincoln Park  41.940298 -87.638117
7                     8.0         Near North Side  41.900033 -87.634497
8                     9.0             Edison Park  42.005733 -87.814016
9                    10.0            Norwood Park  41.985590 -87.800582
10                   11.0          Jefferson Park  41.969738 -87.763118
11                   12.0             Forest Glen  41.991752 -87.751674
12                   13.0              North Park  41.984955 -87.722933
13                   14.0             Albany Park  41.971937 -87.716174
14                   15.0            Portage Park  41.957809 -87.765059
15                   16.0             Irving Park  41.953365 -87.736447
16                   17.0                 Dunning  41.952809 -87.796449
17                   18.0              Montclaire        NaN        NaN
18                   19.0          Belmont Cragin  41.931698 -87.768670
19                   20.0                 Hermosa  41.928643 -87.734502
20                   21.0                Avondale  41.938921 -87.711168
21                   22.0            Logan Square  41.928568 -87.706793
22                   23.0           Humboldt park  41.905767 -87.704174
23                   24.0               West Town  41.901421 -87.686166
24                   25.0                  Austin  41.887876 -87.764851
25                   26.0      West Garfield Park  41.880588 -87.729223
26                   27.0      East Garfield Park  41.880866 -87.702833
27                   28.0          Near West Side  41.880066 -87.666762
28                   29.0          North Lawndale  41.858151 -87.713881
29                   30.0          South Lawndale  41.843644 -87.712554
30                   31.0         Lower West Side  41.847620 -87.671774
31                   32.0                    Loop  41.881609 -87.629457
32                   33.0         Near South Side  41.856700 -87.624774
33                   34.0           Armour Square  41.840033 -87.633107
34                   35.0                 Douglas  41.834857 -87.617954
35                   36.0                 Oakland  41.823653 -87.608242
36                   37.0             Fuller Park  41.818089 -87.632551
37                   38.0         Grand Boulevard  41.813923 -87.617272
38                   39.0                 Kenwood  41.809144 -87.597991
39                   40.0         Washington Park  41.792534 -87.618105
40                   41.0               Hyde Park  41.794446 -87.593924
41                   42.0                Woodlawn  41.779479 -87.599493
42                   43.0             South Shore  41.758728 -87.575283
43                   44.0                 Chatham  41.741145 -87.612548
44                   45.0             Avalon Park  41.745035 -87.588658
45                   46.0           South Chicago  41.734587 -87.551322
46                   47.0                Burnside  41.730035 -87.596714
47                   48.0         Calumet Heights  41.730035 -87.579213
48                   49.0                Roseland  41.701979 -87.625881
49                   50.0                 Pullman  41.704124 -87.598299
50                   51.0           South Deering  41.692236 -87.571703
51                   52.0               East Side  41.708020 -87.534827
52                   53.0            West Pullman  41.675046 -87.637823
53                   54.0               Riverdale  41.665809 -87.605344
54                   55.0               Hege

In [277]:
# drop all neighorhoods with NaN
new_neigh_df.dropna(inplace=True)
new_neigh_df

Community Area Number            Neighborhood   Latitude  Longitude
0                     1.0             Rogers Park  42.010531 -87.670748
1                     2.0              West Ridge  42.003548 -87.696243
2                     3.0                  Uptown  41.966630 -87.655546
3                     4.0          Lincoln Square  41.975990 -87.689616
4                     5.0            North Center  41.956107 -87.679160
5                     6.0               Lake View  41.947050 -87.655429
6                     7.0            Lincoln Park  41.940298 -87.638117
7                     8.0         Near North Side  41.900033 -87.634497
8                     9.0             Edison Park  42.005733 -87.814016
9                    10.0            Norwood Park  41.985590 -87.800582
10                   11.0          Jefferson Park  41.969738 -87.763118
11                   12.0             Forest Glen  41.991752 -87.751674
12                   13.0              North Park  41.984955 -87.722933
13                   14.0             Albany Park  41.971937 -87.716174
14                   15.0            Portage Park  41.957809 -87.765059
15                   16.0             Irving Park  41.953365 -87.736447
16                   17.0                 Dunning  41.952809 -87.796449
18                   19.0          Belmont Cragin  41.931698 -87.768670
19                   20.0                 Hermosa  41.928643 -87.734502
20                   21.0                Avondale  41.938921 -87.711168
21                   22.0            Logan Square  41.928568 -87.706793
22                   23.0           Humboldt park  41.905767 -87.704174
23                   24.0               West Town  41.901421 -87.686166
24                   25.0                  Austin  41.887876 -87.764851
25                   26.0      West Garfield Park  41.880588 -87.729223
26                   27.0      East Garfield Park  41.880866 -87.702833
27                   28.0          Near West Side  41.880066 -87.666762
28                   29.0          North Lawndale  41.858151 -87.713881
29                   30.0          South Lawndale  41.843644 -87.712554
30                   31.0         Lower West Side  41.847620 -87.671774
31                   32.0                    Loop  41.881609 -87.629457
32                   33.0         Near South Side  41.856700 -87.624774
33                   34.0           Armour Square  41.840033 -87.633107
34                   35.0                 Douglas  41.834857 -87.617954
35                   36.0                 Oakland  41.823653 -87.608242
36                   37.0             Fuller Park  41.818089 -87.632551
37                   38.0         Grand Boulevard  41.813923 -87.617272
38                   39.0                 Kenwood  41.809144 -87.597991
39                   40.0         Washington Park  41.792534 -87.618105
40                   41.0               Hyde Park  41.794446 -87.593924
41                   42.0                Woodlawn  41.779479 -87.599493
42                   43.0             South Shore  41.758728 -87.575283
43                   44.0                 Chatham  41.741145 -87.612548
44                   45.0             Avalon Park  41.745035 -87.588658
45                   46.0           South Chicago  41.734587 -87.551322
46                   47.0                Burnside  41.730035 -87.596714
47                   48.0         Calumet Heights  41.730035 -87.579213
48                   49.0                Roseland  41.701979 -87.625881
49                   50.0                 Pullman  41.704124 -87.598299
50                   51.0           South Deering  41.692236 -87.571703
51                   52.0               East Side  41.708020 -87.534827
52                   53.0            West Pullman  41.675046 -87.637823
53                   54.0               Riverdale  41.665809 -87.605344
54                   55.0               Hegewisch  41.653646 -87.546988
55                   56.0          Garfield 

Again, we'll use geopy library to get the latitude and longitude values for the map to center the right location.

In [278]:
new_address = 'Chicago, IL'

geolocator = Nominatim(user_agent="new_city_explorer")
location = geolocator.geocode(new_address)
new_latitude = location.latitude
new_longitude = location.longitude
print('The geograpical coordinate of Chicago are {}, {}.'.format(new_latitude, new_longitude))

The geograpical coordinate of Chicago are 41.8755616, -87.6244212.


In [279]:
# create map of Chicago using latitude and longitude values
map_new_city = folium.Map(location=[new_latitude, new_longitude], zoom_start=10)

# add markers to map
for lat, lng, neighborhood in zip(new_neigh_df['Latitude'], new_neigh_df['Longitude'], new_neigh_df['Neighborhood']):
    label = '{}'.format(neighborhood)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_new_city)  
    
map_new_city

Okay, so far we have identified the neighborhoods in the old and new city by using geopy library. The next step will be to merge the neighborhoods in one dataframe and perform the clustering algorithm to find similiarities between them.

__Merge both city data tables__

Before we can merge both dataframe, we need to do some housing keeping first. Let's start with the old city.

In [280]:
# skip the boroughs
old_neigh_df_tobemerged = old_neigh_df[['Neighborhood', 'Latitude', 'Longitude']].reset_index(drop=True)
old_neigh_df_tobemerged.head()

Neighborhood   Latitude  Longitude
0         Marble Hill  40.876551 -73.910660
1           Chinatown  40.715618 -73.994279
2  Washington Heights  40.851903 -73.936900
3              Inwood  40.867684 -73.921210
4    Hamilton Heights  40.823604 -73.949688

In [281]:
# add the city to the neighborhood column
old_neigh_df_tobemerged['Neighborhood'] = old_neigh_df_tobemerged['Neighborhood'] + ', New York City'
old_neigh_df_tobemerged.head()

Neighborhood   Latitude  Longitude
0         Marble Hill, New York City  40.876551 -73.910660
1           Chinatown, New York City  40.715618 -73.994279
2  Washington Heights, New York City  40.851903 -73.936900
3              Inwood, New York City  40.867684 -73.921210
4    Hamilton Heights, New York City  40.823604 -73.949688

Now, let's do the same with the new city

In [282]:
# add the city to the neighborhood column
new_neigh_df_tobemerged = new_neigh_df[['Neighborhood', 'Latitude', 'Longitude']].reset_index(drop=True)
new_neigh_df_tobemerged['Neighborhood'] = new_neigh_df_tobemerged['Neighborhood'] + ', Chicago'
new_neigh_df_tobemerged.head()

Neighborhood   Latitude  Longitude
0     Rogers Park, Chicago  42.010531 -87.670748
1      West Ridge, Chicago  42.003548 -87.696243
2          Uptown, Chicago  41.966630 -87.655546
3  Lincoln Square, Chicago  41.975990 -87.689616
4    North Center, Chicago  41.956107 -87.679160

__Combine data from multiple tables__

In [283]:
# put the rows of both dataframes into a new dataframe
merged_df = pd.concat([old_neigh_df_tobemerged, new_neigh_df_tobemerged], axis=0).reset_index(drop=True)
merged_df

Neighborhood   Latitude  Longitude
0            Marble Hill, New York City  40.876551 -73.910660
1              Chinatown, New York City  40.715618 -73.994279
2     Washington Heights, New York City  40.851903 -73.936900
3                 Inwood, New York City  40.867684 -73.921210
4       Hamilton Heights, New York City  40.823604 -73.949688
5         Manhattanville, New York City  40.816934 -73.957385
6         Central Harlem, New York City  40.815976 -73.943211
7            East Harlem, New York City  40.792249 -73.944182
8        Upper East Side, New York City  40.775639 -73.960508
9              Yorkville, New York City  40.775930 -73.947118
10            Lenox Hill, New York City  40.768113 -73.958860
11      Roosevelt Island, New York City  40.762160 -73.949168
12       Upper West Side, New York City  40.787658 -73.977059
13        Lincoln Square, New York City  40.773529 -73.985338
14               Clinton, New York City  40.759101 -73.996119
15               Midtown, New York City  40.754691 -73.981669
16           Murray Hill, New York City  40.748303 -73.978332
17               Chelsea, New York City  40.744035 -74.003116
18     Greenwich Village, New York City  40.726933 -73.999914
19          East Village, New York City  40.727847 -73.982226
20       Lower East Side, New York City  40.717807 -73.980890
21               Tribeca, New York City  40.721522 -74.010683
22          Little Italy, New York City  40.719324 -73.997305
23                  Soho, New York City  40.722184 -74.000657
24          West Village, New York City  40.734434 -74.006180
25      Manhattan Valley, New York City  40.797307 -73.964286
26   Morningside Heights, New York City  40.808000 -73.963896
27              Gramercy, New York City  40.737210 -73.981376
28     Battery Park City, New York City  40.711932 -74.016869
29    Financial District, New York City  40.707107 -74.010665
30         Carnegie Hill, New York City  40.782683 -73.953256
31                  Noho, New York City  40.723259 -73.988434
32          Civic Center, New York City  40.715229 -74.005415
33         Midtown South, New York City  40.748510 -73.988713
34          Sutton Place, New York City  40.760280 -73.963556
35            Turtle Bay, New York City  40.752042 -73.967708
36            Tudor City, New York City  40.746917 -73.971219
37       Stuyvesant Town, New York City  40.731000 -73.974052
38              Flatiron, New York City  40.739673 -73.990947
39          Hudson Yards, New York City  40.756658 -74.000111
40                 Rogers Park, Chicago  42.010531 -87.670748
41                  West Ridge, Chicago  42.003548 -87.696243
42                      Uptown, Chicago  41.966630 -87.655546
43              Lincoln Square, Chicago  41.975990 -87.689616
44                North Center, Chicago  41.956107 -87.679160
45                   Lake View, Chicago  41.947050 -87.655429
46                Lincoln Park, Chicago  41.940298 -87.638117
47             Near North Side, Chicago  41.900033 -87.634497
48                 Edison Park, Chicago  42.005733 -87.814016
49                Norwood Park, Chicago  41.985590 -87.800582
50              Jefferson Park, Chicago  41.969738 -87.763118
51                 Forest Glen, Chicago  41.991752 -87.751674
52                  North Park, Chicago  41.984955 -87.722933
53                 Albany Park, Chicago  41.971937 -87.716174
54                Portage Park, Chicago  41.957809 -87.765059
55                 Irving Park, Chicago  41.953365 -87.736447
56                     Dunning, Chicago  41.952809 -87.796449
57              Belmont Cragin, Chicago  41.931698 -87.768670
58                     Hermosa, Chicago  41.928643 -87.734502
59                    Avondale, Chicago  41.938921 -87.711168
60                Logan Square, Chicago  41.928568 -87.706793
61               Humboldt park, Chicago  41.905767 -87.704174
62                   West Town, Chicago  41.901421 -87.686166
63                      Austin, Chicago  41.887876 -87.7648

In [284]:
merged_df.shape

(115, 3)

We have 115 neighborhoods in total. As we saw above, in Manhattan there are 40 and in Chicago 75.

Next, we are going to start utilizing the Foursquare API to explore the neighborhoods and segment them.

#### 3. Use the Foursquare API to get location data of the venues in all the neighborhoods.

In [285]:
CLIENT_ID = 'QZERFRNDH5KHBJXQE330T5EANYUDOWEU4RKJ2VJZNVZETB3T' # your Foursquare ID
CLIENT_SECRET = 'LEZD1ZQQNICFJKRBVGA4UBYCW23OZN5U1GI0TB2LEJAHKVFZ' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: QZERFRNDH5KHBJXQE330T5EANYUDOWEU4RKJ2VJZNVZETB3T
CLIENT_SECRET:LEZD1ZQQNICFJKRBVGA4UBYCW23OZN5U1GI0TB2LEJAHKVFZ


In [286]:
def getNearbyVenues(names, latitudes, longitudes, radius=500, LIMIT=100):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [287]:
neigh_venues = getNearbyVenues(names=merged_df['Neighborhood'],
                                   latitudes=merged_df['Latitude'],
                                   longitudes=merged_df['Longitude']
                                  )

Marble Hill, New York City
Chinatown, New York City
Washington Heights, New York City
Inwood, New York City
Hamilton Heights, New York City
Manhattanville, New York City
Central Harlem, New York City
East Harlem, New York City
Upper East Side, New York City
Yorkville, New York City
Lenox Hill, New York City
Roosevelt Island, New York City
Upper West Side, New York City
Lincoln Square, New York City
Clinton, New York City
Midtown, New York City
Murray Hill, New York City
Chelsea, New York City
Greenwich Village, New York City
East Village, New York City
Lower East Side, New York City
Tribeca, New York City
Little Italy, New York City
Soho, New York City
West Village, New York City
Manhattan Valley, New York City
Morningside Heights, New York City
Gramercy, New York City
Battery Park City, New York City
Financial District, New York City
Carnegie Hill, New York City
Noho, New York City
Civic Center, New York City
Midtown South, New York City
Sutton Place, New York City
Turtle Bay, New Yor

In [288]:
# Let's check the size of the resulting dataframe
print(neigh_venues.shape)
neigh_venues.head()

(4444, 7)


Neighborhood  Neighborhood Latitude  Neighborhood Longitude  \
0  Marble Hill, New York City              40.876551               -73.91066   
1  Marble Hill, New York City              40.876551               -73.91066   
2  Marble Hill, New York City              40.876551               -73.91066   
3  Marble Hill, New York City              40.876551               -73.91066   
4  Marble Hill, New York City              40.876551               -73.91066   

           Venue  Venue Latitude  Venue Longitude Venue Category  
0       Arturo's       40.874412       -73.910271    Pizza Place  
1    Bikram Yoga       40.876844       -73.906204    Yoga Studio  
2  Tibbett Diner       40.880404       -73.908937          Diner  
3        Dunkin'       40.877136       -73.906666     Donut Shop  
4      Starbucks       40.877531       -73.905582    Coffee Shop

We have a total of 4444 venues in the 115 neighborhoods in Manhattan and Chicago.

In [289]:
neigh_venues.groupby('Neighborhood').count().sort_values(by=['Venue'], ascending=False)

Neighborhood Latitude  \
Neighborhood                                                
Yorkville, New York City                              100   
Noho, New York City                                   100   
Financial District, New York City                     100   
Lenox Hill, New York City                             100   
East Village, New York City                           100   
Little Italy, New York City                           100   
Loop, Chicago                                         100   
Clinton, New York City                                100   
Chinatown, New York City                              100   
Chelsea, New York City                                100   
Midtown, New York City                                100   
Greenwich Village, New York City                      100   
Turtle Bay, New York City                             100   
West Village, New York City                           100   
Flatiron, New York City                                97   
Lincoln Square, New York City                          95   
Sutton Place, New York City                            92   
Upper East Side, New York City                         91   
Civic Center, New York City                            90   
Washington Heights, New York City                      89   
Midtown South, New York City                           86   
Carnegie Hill, New York City                           86   
Murray Hill, New York City                             83   
Logan Square, Chicago                                  78   
Tribeca, New York City                                 75   
Tudor City, New York City                              75   
Uptown, Chicago                                        71   
Soho, New York City                                    70   
Gramercy, New York City                                70   
North Center, Chicago                                  68   
Lake View, Chicago                                     67   
Upper West Side, New York City                         66   
Hamilton Heights, New York City                        59   
Battery Park City, New York City                       59   
Edgewater, Chicago                                     59   
Inwood, New York City                                  56   
Hudson Yards, New York City                            53   
Near South Side, Chicago                               52   
Lower East Side, New York City                         47   
Lincoln Square, Chicago                                46   
Central Harlem, New York City                          45   
Manhattanville, New York City                          44   
East Harlem, New York City                             41   
Douglas, Chicago                                       40   
Morningside Heights, New York City                     39   
Manhattan Valley, New York City                        37   
Bridgeport, Chicago                                    36   
West Town, Chicago                                     33   
Rogers Park, Chicago                                   33   
Jefferson Park, Chicago                                31   
Edison Park, Chicago                                   29   
Avondale, Chicago                                      29   
O'Hare, Chicago                                        28   
Hyde Park, Chicago                                     28   
Roosevelt Island, New York City                        25   
Marble Hill, New York City                             25   
Near West Side, Chicago                                25   
Near North Side, Chicago                               24   
Irving Park, Chicago                                   23   
Kenwood, Chicago                                       21   
Portage Park, Chicago                                  21   
Archer Heights, Chicago                                18   
Belmont Cragin, Chicago                                18   
West Elsdon, Chicago                                   18   
West Garfi

In [290]:
print('There are {} uniques categories.'.format(len(neigh_venues['Venue Category'].unique())))

There are 368 uniques categories.


Out of the 4444 venues, we can group them into 368 distinct categories. As from the table above, you can also see that the neighborhoods with highest count of venues are mostly in Manhattan. Loop in Chicago is the only neighborhood that has more than 100 venues to offer. It looks like someone moving from Manhattan to Chicago will find himself in a city that is not as exciting as he or she might expect. 

__Analyze Each Neighborhood__

Now, let's take a deeper dive into what each neighborhood has to offer

In [291]:
# one hot encoding
neigh_onehot = pd.get_dummies(neigh_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
neigh_onehot['Neighborhood'] = neigh_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [neigh_onehot.columns[-1]] + list(neigh_onehot.columns[:-1])
neigh_onehot = neigh_onehot[fixed_columns]

neigh_onehot.head()

Neighborhood  ATM  Accessories Store  Adult Boutique  \
0  Marble Hill, New York City    0                  0               0   
1  Marble Hill, New York City    0                  0               0   
2  Marble Hill, New York City    0                  0               0   
3  Marble Hill, New York City    0                  0               0   
4  Marble Hill, New York City    0                  0               0   

   Afghan Restaurant  African Restaurant  Airport Lounge  Airport Service  \
0                  0                   0               0                0   
1                  0                   0               0                0   
2                  0                   0               0                0   
3                  0                   0               0                0   
4                  0                   0               0                0   

   American Restaurant  Antique Shop  Arcade  Arepa Restaurant  \
0                    0             0       0                 0   
1                    0             0       0                 0   
2                    0             0       0                 0   
3                    0             0       0                 0   
4                    0             0       0                 0   

   Argentinian Restaurant  Art Gallery  Art Museum  Arts & Crafts Store  \
0                       0            0           0                    0   
1                       0            0           0                    0   
2                       0            0           0                    0   
3                       0            0           0                    0   
4                       0            0           0                    0   

   Asian Restaurant  Athletics & Sports  Auditorium  Australian Restaurant  \
0                 0                   0           0                      0   
1                 0                   0           0                      0   
2                 0                   0           0                      0   
3                 0                   0           0                      0   
4                 0                   0           0                      0   

   Austrian Restaurant  Auto Dealership  Automotive Shop  BBQ Joint  \
0                    0                0                0          0   
1                    0                0                0          0   
2                    0                0                0          0   
3                    0                0                0          0   
4                    0                0                0          0   

   Baby Store  Bagel Shop  Bakery  Bank  Bar  Baseball Field  \
0           0           0       0     0    0               0   
1           0           0       0     0    0               0   
2           0           0       0     0    0               0   
3           0           0       0     0    0               0   
4           0           0       0     0    0               0   

   Baseball Stadium  Basketball Court  Basketball Stadium  Beach  Beer Bar  \
0                 0                 0                   0      0         0   
1                 0                 0                   0      0         0   
2                 0                 0                   0      0         0   
3                 0                 0                   0      0         0   
4                 0                 0                   0      0         0   

   Beer Garden  Beer Store  Big Box Store  Bike Rental / Bike Share  \
0            0           0              0                         0   
1            0           0              0                         0   
2            0           0              0                         0   
3            0           0              0                         0   
4            0           0              0                         0   

   Bike Shop  Bike Trail  Bistro  Board Shop  Boat or Ferry  Bookstore  \
0          0    

Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [292]:
neigh_grouped = neigh_onehot.groupby('Neighborhood').mean().reset_index()
neigh_grouped

Neighborhood       ATM  Accessories Store  \
0                  Albany Park, Chicago  0.000000           0.000000   
1               Archer Heights, Chicago  0.000000           0.000000   
2                Armour Square, Chicago  0.000000           0.000000   
3                      Ashburn, Chicago  0.000000           0.000000   
4               Auburn Gresham, Chicago  0.000000           0.000000   
5                       Austin, Chicago  0.000000           0.000000   
6                  Avalon Park, Chicago  0.083333           0.000000   
7                     Avondale, Chicago  0.000000           0.000000   
8      Battery Park City, New York City  0.000000           0.000000   
9               Belmont Cragin, Chicago  0.000000           0.000000   
10                     Beverly, Chicago  0.000000           0.000000   
11                  Bridgeport, Chicago  0.000000           0.000000   
12               Brighton Park, Chicago  0.000000           0.000000   
13                    Burnside, Chicago  0.000000           0.000000   
14             Calumet Heights, Chicago  0.000000           0.000000   
15         Carnegie Hill, New York City  0.000000           0.000000   
16        Central Harlem, New York City  0.000000           0.000000   
17                     Chatham, Chicago  0.000000           0.000000   
18               Chelsea, New York City  0.000000           0.000000   
19                Chicago Lawn, Chicago  0.000000           0.000000   
20             Chinatown, New York City  0.000000           0.000000   
21          Civic Center, New York City  0.000000           0.000000   
22                    Clearing, Chicago  0.000000           0.000000   
23               Clinton, New York City  0.000000           0.000000   
24                     Douglas, Chicago  0.000000           0.000000   
25                     Dunning, Chicago  0.000000           0.000000   
26          East Garfield Park, Chicago  0.000000           0.000000   
27           East Harlem, New York City  0.000000           0.000000   
28                   East Side, Chicago  0.000000           0.000000   
29          East Village, New York City  0.000000           0.000000   
30                   Edgewater, Chicago  0.000000           0.000000   
31                 Edison Park, Chicago  0.000000           0.000000   
32                   Englewood, Chicago  0.066667           0.000000   
33    Financial District, New York City  0.000000           0.000000   
34              Flatiron, New York City  0.000000           0.000000   
35                 Forest Glen, Chicago  0.000000           0.000000   
36                 Fuller Park, Chicago  0.000000           0.000000   
37                   Gage Park, Chicago  0.000000           0.000000   
38              Garfield Ridge, Chicago  0.000000           0.000000   
39              Gramercy, New York City  0.000000           0.000000   
40             Grand Boulevard, Chicago  0.000000           0.000000   
41      Greater Grand Crossing, Chicago  0.000000           0.000000   
42     Greenwich Village, New York City  0.000000           0.000000   
43      Hamilton Heights, New York City  0.000000           0.000000   
44                   Hegewisch, Chicago  0.000000           0.000000   
45                     Hermosa, Chicago  0.000000           0.000000   
46          Hudson Yards, New York City  0.000000           0.000000   
47               Humboldt park, Chicago  0.000000           0.000000   
48                   Hyde Park, Chicago  0.000000           0.000000   
49                Inwood, New York City  0.000000           0.000000   
50                 Irving Park, Chicago  0.000000           0.000000   
51              Jefferson Park, Chicago  0.000000           0.000000   
52                     Kenwood, Chicago  0.000000           0.000000   
53                   Lake View, Chicago  0.014925           0.000000   
54            Lenox Hill, New York City  0.000000           0.00000

Let's print each neighborhood along with the top 5 most common venues

In [293]:
num_top_venues = 5

for hood in neigh_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = neigh_grouped[neigh_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Albany Park, Chicago----
                venue  freq
0              Bakery  0.08
1   Mobile Phone Shop  0.08
2       Grocery Store  0.08
3  Chinese Restaurant  0.08
4          Donut Shop  0.08


----Archer Heights, Chicago----
                venue  freq
0  Mexican Restaurant  0.17
1   Mobile Phone Shop  0.11
2       Grocery Store  0.11
3                 Bar  0.06
4      Sandwich Place  0.06


----Armour Square, Chicago----
                venue  freq
0  Chinese Restaurant  0.25
1    Asian Restaurant  0.17
2       Hot Dog Joint  0.08
3      Sandwich Place  0.08
4       Tanning Salon  0.08


----Ashburn, Chicago----
                        venue  freq
0             Automotive Shop  0.33
1  Construction & Landscaping  0.17
2          Italian Restaurant  0.17
3              Cosmetics Shop  0.17
4          Light Rail Station  0.17


----Auburn Gresham, Chicago----
              venue  freq
0              Park  0.25
1              Pool  0.25
2  Basketball Court  0.25
3    Discount Store

                        venue  freq
0         American Restaurant  0.12
1         Fried Chicken Joint  0.06
2  Construction & Landscaping  0.06
3                        Farm  0.06
4               Grocery Store  0.06


----Noho, New York City----
                 venue  freq
0   Italian Restaurant  0.06
1  Japanese Restaurant  0.05
2          Coffee Shop  0.05
3       Sandwich Place  0.04
4        Grocery Store  0.04


----North Center, Chicago----
         venue  freq
0          Bar  0.09
1  Coffee Shop  0.06
2      Brewery  0.04
3         Bank  0.04
4   Restaurant  0.03


----North Lawndale, Chicago----
                        venue  freq
0                        Park  0.25
1  Construction & Landscaping  0.25
2          Seafood Restaurant  0.25
3               Train Station  0.25
4                Noodle House  0.00


----North Park, Chicago----
             venue  freq
0             Park  0.25
1  Nature Preserve  0.25
2      Bus Station  0.25
3   Gymnastics Gym  0.25
4              AT

Again, from a quick glance at the top 5 most common venues it looks to me as some neighborhoods of Chicago are a little bit sleepy. Take, for example, Woodlawn (way at the end) - it has some parks and coffee shops, but nothing more. Could be a perfect fit for a stressed out banker from Wall Street. 

First, let's write a function to sort the venues in descending order.

In [294]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

Now let's create the new dataframe and display the top 10 venues for each neighborhood.


In [295]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = neigh_grouped['Neighborhood']

for ind in np.arange(neigh_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(neigh_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

Neighborhood 1st Most Common Venue       2nd Most Common Venue  \
0     Albany Park, Chicago     Mobile Phone Shop                Cocktail Bar   
1  Archer Heights, Chicago    Mexican Restaurant           Mobile Phone Shop   
2   Armour Square, Chicago    Chinese Restaurant            Asian Restaurant   
3         Ashburn, Chicago       Automotive Shop  Construction & Landscaping   
4  Auburn Gresham, Chicago                  Pool                        Park   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0            Donut Shop         Grocery Store                Bakery   
1         Grocery Store           Coffee Shop           Candy Store   
2        Cosmetics Shop         Hot Dog Joint    Italian Restaurant   
3        Cosmetics Shop    Italian Restaurant    Light Rail Station   
4        Discount Store      Basketball Court           Dry Cleaner   

  6th Most Common Venue        7th Most Common Venue  \
0    Chinese Restaurant               Sandwich Place   
1           Gas Station         Gym / Fitness Center   
2        Sandwich Place                  Gas Station   
3            Eye Doctor               Duty-free Shop   
4        Duty-free Shop  Eastern European Restaurant   

         8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
0                        Diner     Korean Restaurant            Karaoke Bar  
1               Sandwich Place    Italian Restaurant                   Bank  
2                Tanning Salon      Business Service            Yoga Studio  
3  Eastern European Restaurant     Electronics Store    Empanada Restaurant  
4            Electronics Store   Empanada Restaurant     English Restaurant

Now we have the top 10 venues for all neighborhoods in our example. We can move on to cluster them by using the k-means algorithm.

In [296]:
# Let's make a copy by writing to a csv-file for further usage.
neigh_grouped.to_csv('neigh_grouped.csv', encoding='utf-8', index=False)
neighborhoods_venues_sorted.to_csv('neighborhoods_venues_sorted.csv', encoding='utf-8', index=False)

#### 4. Clustering of the neighborhoods with a clustering algorithm to find similar neighborhoods in both cities.


In [297]:
# re-load the csv-file 
df_neigh_grouped = pd.read_csv('neigh_grouped.csv')
df_neigh_grouped.head()

Neighborhood  ATM  Accessories Store  Adult Boutique  \
0     Albany Park, Chicago  0.0                0.0             0.0   
1  Archer Heights, Chicago  0.0                0.0             0.0   
2   Armour Square, Chicago  0.0                0.0             0.0   
3         Ashburn, Chicago  0.0                0.0             0.0   
4  Auburn Gresham, Chicago  0.0                0.0             0.0   

   Afghan Restaurant  African Restaurant  Airport Lounge  Airport Service  \
0                0.0                 0.0             0.0              0.0   
1                0.0                 0.0             0.0              0.0   
2                0.0                 0.0             0.0              0.0   
3                0.0                 0.0             0.0              0.0   
4                0.0                 0.0             0.0              0.0   

   American Restaurant  Antique Shop  Arcade  Arepa Restaurant  \
0                  0.0           0.0     0.0               0.0   
1                  0.0           0.0     0.0               0.0   
2                  0.0           0.0     0.0               0.0   
3                  0.0           0.0     0.0               0.0   
4                  0.0           0.0     0.0               0.0   

   Argentinian Restaurant  Art Gallery  Art Museum  Arts & Crafts Store  \
0                     0.0          0.0         0.0                  0.0   
1                     0.0          0.0         0.0                  0.0   
2                     0.0          0.0         0.0                  0.0   
3                     0.0          0.0         0.0                  0.0   
4                     0.0          0.0         0.0                  0.0   

   Asian Restaurant  Athletics & Sports  Auditorium  Australian Restaurant  \
0          0.000000                 0.0         0.0                    0.0   
1          0.000000                 0.0         0.0                    0.0   
2          0.166667                 0.0         0.0                    0.0   
3          0.000000                 0.0         0.0                    0.0   
4          0.000000                 0.0         0.0                    0.0   

   Austrian Restaurant  Auto Dealership  Automotive Shop  BBQ Joint  \
0                  0.0              0.0         0.000000        0.0   
1                  0.0              0.0         0.000000        0.0   
2                  0.0              0.0         0.000000        0.0   
3                  0.0              0.0         0.333333        0.0   
4                  0.0              0.0         0.000000        0.0   

   Baby Store  Bagel Shop    Bakery      Bank       Bar  Baseball Field  \
0         0.0         0.0  0.083333  0.000000  0.000000             0.0   
1         0.0         0.0  0.000000  0.055556  0.055556             0.0   
2         0.0         0.0  0.000000  0.000000  0.000000             0.0   
3         0.0         0.0  0.000000  0.000000  0.000000             0.0   
4         0.0         0.0  0.000000  0.000000  0.000000             0.0   

   Baseball Stadium  Basketball Court  Basketball Stadium  Beach  Beer Bar  \
0               0.0              0.00                 0.0    0.0       0.0   
1               0.0              0.00                 0.0    0.0       0.0   
2               0.0              0.00                 0.0    0.0       0.0   
3               0.0              0.00                 0.0    0.0       0.0   
4               0.0              0.25                 0.0    0.0       0.0   

   Beer Garden  Beer Store  Big Box Store  Bike Rental / Bike Share  \
0          0.0         0.0       0.000000                       0.0   
1          0.0         0.0       0.055556                       0.0   
2          0.0         0.0       0.000000                       0.0   
3          0.0         0.0       0.000000                       0.0   
4          0.0         0.0       0.000000                       0.0   

   Bike Shop  Bike Trail  Bistro  Board

Run k-means to cluster the neighborhood into 5 clusters.

In [298]:
# set number of clusters
kclusters = 5

neigh_grouped_clustering = df_neigh_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(neigh_grouped_clustering)


# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

array([1, 4, 1, 1, 0, 1, 4, 1, 1, 4])

In [299]:
df_neighborhoods_venues_sorted = pd.read_csv('neighborhoods_venues_sorted.csv')
df_neighborhoods_venues_sorted.head()

Neighborhood 1st Most Common Venue       2nd Most Common Venue  \
0     Albany Park, Chicago     Mobile Phone Shop                Cocktail Bar   
1  Archer Heights, Chicago    Mexican Restaurant           Mobile Phone Shop   
2   Armour Square, Chicago    Chinese Restaurant            Asian Restaurant   
3         Ashburn, Chicago       Automotive Shop  Construction & Landscaping   
4  Auburn Gresham, Chicago                  Pool                        Park   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0            Donut Shop         Grocery Store                Bakery   
1         Grocery Store           Coffee Shop           Candy Store   
2        Cosmetics Shop         Hot Dog Joint    Italian Restaurant   
3        Cosmetics Shop    Italian Restaurant    Light Rail Station   
4        Discount Store      Basketball Court           Dry Cleaner   

  6th Most Common Venue        7th Most Common Venue  \
0    Chinese Restaurant               Sandwich Place   
1           Gas Station         Gym / Fitness Center   
2        Sandwich Place                  Gas Station   
3            Eye Doctor               Duty-free Shop   
4        Duty-free Shop  Eastern European Restaurant   

         8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
0                        Diner     Korean Restaurant            Karaoke Bar  
1               Sandwich Place    Italian Restaurant                   Bank  
2                Tanning Salon      Business Service            Yoga Studio  
3  Eastern European Restaurant     Electronics Store    Empanada Restaurant  
4            Electronics Store   Empanada Restaurant     English Restaurant

Let's create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.

In [300]:
# add clustering labels
df_neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

# merge to add latitude/longitude for each neighborhood
merged_df = merged_df.join(df_neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

merged_df # check the last columns!

Neighborhood   Latitude  Longitude  Cluster Labels  \
0            Marble Hill, New York City  40.876551 -73.910660             1.0   
1              Chinatown, New York City  40.715618 -73.994279             1.0   
2     Washington Heights, New York City  40.851903 -73.936900             1.0   
3                 Inwood, New York City  40.867684 -73.921210             1.0   
4       Hamilton Heights, New York City  40.823604 -73.949688             1.0   
5         Manhattanville, New York City  40.816934 -73.957385             1.0   
6         Central Harlem, New York City  40.815976 -73.943211             1.0   
7            East Harlem, New York City  40.792249 -73.944182             4.0   
8        Upper East Side, New York City  40.775639 -73.960508             1.0   
9              Yorkville, New York City  40.775930 -73.947118             1.0   
10            Lenox Hill, New York City  40.768113 -73.958860             1.0   
11      Roosevelt Island, New York City  40.762160 -73.949168             1.0   
12       Upper West Side, New York City  40.787658 -73.977059             1.0   
13        Lincoln Square, New York City  40.773529 -73.985338             1.0   
14               Clinton, New York City  40.759101 -73.996119             1.0   
15               Midtown, New York City  40.754691 -73.981669             1.0   
16           Murray Hill, New York City  40.748303 -73.978332             1.0   
17               Chelsea, New York City  40.744035 -74.003116             1.0   
18     Greenwich Village, New York City  40.726933 -73.999914             1.0   
19          East Village, New York City  40.727847 -73.982226             1.0   
20       Lower East Side, New York City  40.717807 -73.980890             1.0   
21               Tribeca, New York City  40.721522 -74.010683             1.0   
22          Little Italy, New York City  40.719324 -73.997305             1.0   
23                  Soho, New York City  40.722184 -74.000657             1.0   
24          West Village, New York City  40.734434 -74.006180             1.0   
25      Manhattan Valley, New York City  40.797307 -73.964286             1.0   
26   Morningside Heights, New York City  40.808000 -73.963896             1.0   
27              Gramercy, New York City  40.737210 -73.981376             1.0   
28     Battery Park City, New York City  40.711932 -74.016869             1.0   
29    Financial District, New York City  40.707107 -74.010665             1.0   
30         Carnegie Hill, New York City  40.782683 -73.953256             1.0   
31                  Noho, New York City  40.723259 -73.988434             1.0   
32          Civic Center, New York City  40.715229 -74.005415             1.0   
33         Midtown South, New York City  40.748510 -73.988713             1.0   
34          Sutton Place, New York City  40.760280 -73.963556             1.0   
35            Turtle Bay, New York City  40.752042 -73.967708             1.0   
36            Tudor City, New York City  40.746917 -73.971219             1.0   
37       Stuyvesant Town, New York City  40.731000 -73.974052             1.0   
38              Flatiron, New York City  40.739673 -73.990947             1.0   
39          Hudson Yards, New York City  40.756658 -74.000111             1.0   
40                 Rogers Park, Chicago  42.010531 -87.670748             4.0   
41                  West Ridge, Chicago  42.003548 -87.696243             1.0   
42                      Uptown, Chicago  41.966630 -87.655546             1.0   
43              Lincoln Square, Chicago  41.975990 -87.689616             1.0   
44                North Center, Chicago  41.956107 -87.679160             1.0   
45                   Lake View, Chicago  41.947050 -87.655429             1.0   
46                Lincoln Park, Chicago  41.940298 -87.638117             1.0   
47             Near North Side, Chicago  41.900033 -87.634497             1.0   
48                 Edison Park, Chicago  42.005733 -87.814

In [301]:
# change data type for algorithm to work properly
merged_df['Cluster Labels'] = merged_df['Cluster Labels'].fillna(0.0).astype(int)
print(merged_df.shape)
merged_df.head()

(115, 14)


Neighborhood   Latitude  Longitude  Cluster Labels  \
0         Marble Hill, New York City  40.876551 -73.910660               1   
1           Chinatown, New York City  40.715618 -73.994279               1   
2  Washington Heights, New York City  40.851903 -73.936900               1   
3              Inwood, New York City  40.867684 -73.921210               1   
4    Hamilton Heights, New York City  40.823604 -73.949688               1   

  1st Most Common Venue 2nd Most Common Venue 3rd Most Common Venue  \
0        Sandwich Place           Coffee Shop                   Gym   
1    Chinese Restaurant                Bakery          Cocktail Bar   
2                  Café                Bakery         Grocery Store   
3    Mexican Restaurant                  Café                Bakery   
4           Pizza Place           Coffee Shop                  Café   

  4th Most Common Venue 5th Most Common Venue 6th Most Common Venue  \
0              Pharmacy         Deli / Bodega      Department Store   
1   American Restaurant           Coffee Shop                   Spa   
2    Mexican Restaurant    Chinese Restaurant     Mobile Phone Shop   
3           Pizza Place                Lounge            Restaurant   
4    Mexican Restaurant         Deli / Bodega           Yoga Studio   

     7th Most Common Venue 8th Most Common Venue 9th Most Common Venue  \
0                    Diner        Discount Store            Kids Store   
1       Salon / Barbershop          Optical Shop   Shanghai Restaurant   
2  New American Restaurant    Spanish Restaurant           Coffee Shop   
3                 Wine Bar    Frozen Yogurt Shop                  Park   
4                     Park  Caribbean Restaurant                School   

      10th Most Common Venue  
0                 Donut Shop  
1           Asian Restaurant  
2  Latin American Restaurant  
3              Deli / Bodega  
4         Chinese Restaurant

In [302]:
# drop NaN and check shape
merged_df.dropna(inplace=True)
merged_df.shape

(113, 14)

Okay, we have lost 2 neighborhoods due to NaN values.

In [303]:
# separate cities- first the old city
merged_df_old = merged_df[~merged_df['Neighborhood'].str.contains('Chicago')].sort_values(by=['Neighborhood'], ascending=True)
merged_df_old

Neighborhood   Latitude  Longitude  Cluster Labels  \
28    Battery Park City, New York City  40.711932 -74.016869               1   
30        Carnegie Hill, New York City  40.782683 -73.953256               1   
6        Central Harlem, New York City  40.815976 -73.943211               1   
17              Chelsea, New York City  40.744035 -74.003116               1   
1             Chinatown, New York City  40.715618 -73.994279               1   
32         Civic Center, New York City  40.715229 -74.005415               1   
14              Clinton, New York City  40.759101 -73.996119               1   
7           East Harlem, New York City  40.792249 -73.944182               4   
19         East Village, New York City  40.727847 -73.982226               1   
29   Financial District, New York City  40.707107 -74.010665               1   
38             Flatiron, New York City  40.739673 -73.990947               1   
27             Gramercy, New York City  40.737210 -73.981376               1   
18    Greenwich Village, New York City  40.726933 -73.999914               1   
4      Hamilton Heights, New York City  40.823604 -73.949688               1   
39         Hudson Yards, New York City  40.756658 -74.000111               1   
3                Inwood, New York City  40.867684 -73.921210               1   
10           Lenox Hill, New York City  40.768113 -73.958860               1   
13       Lincoln Square, New York City  40.773529 -73.985338               1   
22         Little Italy, New York City  40.719324 -73.997305               1   
20      Lower East Side, New York City  40.717807 -73.980890               1   
25     Manhattan Valley, New York City  40.797307 -73.964286               1   
5        Manhattanville, New York City  40.816934 -73.957385               1   
0           Marble Hill, New York City  40.876551 -73.910660               1   
33        Midtown South, New York City  40.748510 -73.988713               1   
15              Midtown, New York City  40.754691 -73.981669               1   
26  Morningside Heights, New York City  40.808000 -73.963896               1   
16          Murray Hill, New York City  40.748303 -73.978332               1   
31                 Noho, New York City  40.723259 -73.988434               1   
11     Roosevelt Island, New York City  40.762160 -73.949168               1   
23                 Soho, New York City  40.722184 -74.000657               1   
37      Stuyvesant Town, New York City  40.731000 -73.974052               1   
34         Sutton Place, New York City  40.760280 -73.963556               1   
21              Tribeca, New York City  40.721522 -74.010683               1   
36           Tudor City, New York City  40.746917 -73.971219               1   
35           Turtle Bay, New York City  40.752042 -73.967708               1   
8       Upper East Side, New York City  40.775639 -73.960508               1   
12      Upper West Side, New York City  40.787658 -73.977059               1   
2    Washington Heights, New York City  40.851903 -73.936900               1   
24         West Village, New York City  40.734434 -74.006180               1   
9             Yorkville, New York City  40.775930 -73.947118               1   

   1st Most Common Venue 2nd Most Common Venue  \
28                  Park                 Hotel   
30           Coffee Shop                  Café   
6   Gym / Fitness Center    Chinese Restaurant   
17           Art Gallery           Coffee Shop   
1     Chinese Restaurant                Bakery   
32                 Hotel           Coffee Shop   
14               Theater           Coffee Shop   
7     Mexican Restaurant                Bakery   
19           Pizza Place                   Bar   
29           Coffee Shop                 Hotel   
38  Gym / Fitness Center        Cosmetics Shop   
27           Coffee Shop           Pizza Place   
18    Italian Restaurant                  Café   
4            Pizza Place           Coffee Sho

In [304]:
# create map
map_clusters_old = folium.Map(location=[old_latitude, old_longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(merged_df_old['Latitude'], merged_df_old['Longitude'], merged_df_old['Neighborhood'], merged_df_old['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters_old)
       
map_clusters_old

Interestingly, when we put the neighborhoods in Manhattan together with the ones from Chicago, we find that they are quite similar. Almost all of them belong to Cluster 1. East Harlem is the only neighborhood that was put into Cluster 4 and no single one was assigned to Cluter 2 and 3.

In [305]:
# separate cities- now the new city,
merged_df_new = merged_df[~merged_df['Neighborhood'].str.contains('New York')].reset_index(drop=True)
merged_df_new.head()

Neighborhood   Latitude  Longitude  Cluster Labels  \
0     Rogers Park, Chicago  42.010531 -87.670748               4   
1      West Ridge, Chicago  42.003548 -87.696243               1   
2          Uptown, Chicago  41.966630 -87.655546               1   
3  Lincoln Square, Chicago  41.975990 -87.689616               1   
4    North Center, Chicago  41.956107 -87.679160               1   

  1st Most Common Venue 2nd Most Common Venue 3rd Most Common Venue  \
0    Mexican Restaurant           Pizza Place    Chinese Restaurant   
1     Convenience Store              Wine Bar   Fried Chicken Joint   
2           Coffee Shop    Mexican Restaurant           Pizza Place   
3                   Bar        Sandwich Place           Bus Station   
4                   Bar           Coffee Shop               Brewery   

  4th Most Common Venue 5th Most Common Venue 6th Most Common Venue  \
0   American Restaurant         Train Station                Bakery   
1            Eye Doctor   Dumpling Restaurant        Duty-free Shop   
2                   Bar           Music Venue      Sushi Restaurant   
3                  Café        Cosmetics Shop     Korean Restaurant   
4                  Bank              Dive Bar  Gym / Fitness Center   

         7th Most Common Venue 8th Most Common Venue 9th Most Common Venue  \
0                      Theater            Donut Shop        Discount Store   
1  Eastern European Restaurant     Electronics Store   Empanada Restaurant   
2                        Diner  Ethiopian Restaurant         Grocery Store   
3            Convenience Store           Pizza Place              Pharmacy   
4                     Boutique            Restaurant                   Spa   

   10th Most Common Venue  
0                Dive Bar  
1      English Restaurant  
2                  Lounge  
3                    Bank  
4  Furniture / Home Store

In [306]:
# create map
map_clusters_new = folium.Map(location=[new_latitude, new_longitude], zoom_start=10)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(merged_df_new['Latitude'], merged_df_new['Longitude'], merged_df_new['Neighborhood'], merged_df_new['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters_new)
       
map_clusters_new

In contrast to Manhattan, the neighborhoods in Chicago seem to differ quite a lot. Here, we found a higher number of Cluster 0, 1, and 4. Whereas Cluster 2 hat a single neighborhood, Pullman and 3 is assigned to Norwood Park only.  

#### 5. Define each cluster by checking the main characteristics based on venues data.


In [307]:
# let's check out cluster 0
merged_df.loc[merged_df['Cluster Labels'] == 0, merged_df.columns[[0] + list(range(4, merged_df.shape[1]))]]

Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
52        North Park, Chicago           Bus Station        Gymnastics Gym   
61     Humboldt park, Chicago                  Park            Food Truck   
67    North Lawndale, Chicago    Seafood Restaurant         Train Station   
74           Oakland, Chicago                  Park              Boutique   
75       Fuller Park, Chicago  Fast Food Restaurant                  Park   
80          Woodlawn, Chicago                  Park           Coffee Shop   
82           Chatham, Chicago                  Park              Boutique   
86   Calumet Heights, Chicago  Gym / Fitness Center           Bus Station   
109   Auburn Gresham, Chicago                  Pool                  Park   
111  Mount Greenwood, Chicago        Cosmetics Shop                  Park   

    3rd Most Common Venue       4th Most Common Venue  \
52                   Park             Nature Preserve   
61         Baseball Field                      Museum   
67                   Park  Construction & Landscaping   
74             Public Art                       Track   
75         Sandwich Place                 Yoga Studio   
80            Yoga Studio                     Exhibit   
82   Fast Food Restaurant                 Bus Station   
86                   Park               Deli / Bodega   
109        Discount Store            Basketball Court   
111              Vineyard                 Yoga Studio   

          5th Most Common Venue 6th Most Common Venue  \
52                      Exhibit        Duty-free Shop   
61                         Lake                 Beach   
67              Coworking Space               Exhibit   
74               Discount Store           Event Space   
75         Ethiopian Restaurant           Dry Cleaner   
80          Dumpling Restaurant        Duty-free Shop   
82                   Donut Shop        Ice Cream Shop   
86   Financial or Legal Service   Filipino Restaurant   
109                 Dry Cleaner        Duty-free Shop   
111                     Exhibit   Dumpling Restaurant   

           7th Most Common Venue        8th Most Common Venue  \
52   Eastern European Restaurant            Electronics Store   
61                History Museum                         Café   
67           Dumpling Restaurant               Duty-free Shop   
74           Dumpling Restaurant               Duty-free Shop   
75           Dumpling Restaurant               Duty-free Shop   
80   Eastern European Restaurant            Electronics Store   
82                      Creperie                   Eye Doctor   
86           Dumpling Restaurant               Duty-free Shop   
109  Eastern European Restaurant            Electronics Store   
111               Duty-free Shop  Eastern European Restaurant   

           9th Most Common Venue       10th Most Common Venue  
52           Empanada Restaurant           English Restaurant  
61                  Soccer Field                  Yoga Studio  
67   Eastern European Restaurant            Electronics Store  
74   Eastern European Restaurant            Electronics Store  
75   Eastern European Restaurant            Electronics Store  
80           Empanada Restaurant           English Restaurant  
82   Eastern European Restaurant            Electronics Store  
86                   Fish Market  Eastern European Restaurant  
109          Empanada Restaurant           English Restaurant  
111            Electronics Store          Empanada Restaurant

In [308]:
# let's check out cluster 1
merged_df.loc[merged_df['Cluster Labels'] == 1, merged_df.columns[[0] + list(range(4, merged_df.shape[1]))]]

Neighborhood          1st Most Common Venue  \
0            Marble Hill, New York City                 Sandwich Place   
1              Chinatown, New York City             Chinese Restaurant   
2     Washington Heights, New York City                           Café   
3                 Inwood, New York City             Mexican Restaurant   
4       Hamilton Heights, New York City                    Pizza Place   
5         Manhattanville, New York City                    Coffee Shop   
6         Central Harlem, New York City           Gym / Fitness Center   
8        Upper East Side, New York City             Italian Restaurant   
9              Yorkville, New York City             Italian Restaurant   
10            Lenox Hill, New York City             Italian Restaurant   
11      Roosevelt Island, New York City                           Park   
12       Upper West Side, New York City             Italian Restaurant   
13        Lincoln Square, New York City                           Café   
14               Clinton, New York City                        Theater   
15               Midtown, New York City                          Hotel   
16           Murray Hill, New York City                 Sandwich Place   
17               Chelsea, New York City                    Art Gallery   
18     Greenwich Village, New York City             Italian Restaurant   
19          East Village, New York City                    Pizza Place   
20       Lower East Side, New York City                    Art Gallery   
21               Tribeca, New York City                           Park   
22          Little Italy, New York City             Chinese Restaurant   
23                  Soho, New York City             Italian Restaurant   
24          West Village, New York City                       Wine Bar   
25      Manhattan Valley, New York City                    Yoga Studio   
26   Morningside Heights, New York City                           Park   
27              Gramercy, New York City                    Coffee Shop   
28     Battery Park City, New York City                           Park   
29    Financial District, New York City                    Coffee Shop   
30         Carnegie Hill, New York City                    Coffee Shop   
31                  Noho, New York City             Italian Restaurant   
32          Civic Center, New York City                          Hotel   
33         Midtown South, New York City              Korean Restaurant   
34          Sutton Place, New York City             Italian Restaurant   
35            Turtle Bay, New York City             Italian Restaurant   
36            Tudor City, New York City                           Park   
37       Stuyvesant Town, New York City                           Park   
38              Flatiron, New York City           Gym / Fitness Center   
39          Hudson Yards, New York City            American Restaurant   
41                  West Ridge, Chicago              Convenience Store   
42                      Uptown, Chicago                    Coffee Shop   
43              Lincoln Square, Chicago                            Bar   
44                North Center, Chicago                            Bar   
45                   Lake View, Chicago                            Bar   
46                Lincoln Park, Chicago                        Dog Run   
47             Near North Side, Chicago                    Yoga Studio   
48                 Edison Park, Chicago                            Bar   
50              Jefferson Park, Chicago                            Bar   
53                 Albany Park, Chicago              Mobile Phone Shop   
54                Portage Park, Chicago             Italian Restaurant   
55                 Irving Park, Chicago                    Coffee Shop   
56                     Dunning, Chicago                    Candy Store   
59                    Avondale, Chicago                           Park   
60                Logan Square,

In [309]:
# let's check out cluster 2
merged_df.loc[merged_df['Cluster Labels'] == 2, merged_df.columns[[0] + list(range(4, merged_df.shape[1]))]]

Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
88  Pullman, Chicago        History Museum           Yoga Studio   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
88               Exhibit   Dumpling Restaurant        Duty-free Shop   

          6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
88  Eastern European Restaurant     Electronics Store   Empanada Restaurant   

   9th Most Common Venue 10th Most Common Venue  
88    English Restaurant   Ethiopian Restaurant

In [310]:
# let's check out cluster 3
merged_df.loc[merged_df['Cluster Labels'] == 3, merged_df.columns[[0] + list(range(4, merged_df.shape[1]))]]

Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
49  Norwood Park, Chicago                  Park           Yoga Studio   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
49               Exhibit   Dumpling Restaurant        Duty-free Shop   

          6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
49  Eastern European Restaurant     Electronics Store   Empanada Restaurant   

   9th Most Common Venue 10th Most Common Venue  
49    English Restaurant   Ethiopian Restaurant

In [311]:
# let's check out cluster 4
merged_df.loc[merged_df['Cluster Labels'] == 4, merged_df.columns[[0] + list(range(4, merged_df.shape[1]))]]

Neighborhood 1st Most Common Venue  \
7         East Harlem, New York City    Mexican Restaurant   
40              Rogers Park, Chicago    Mexican Restaurant   
51              Forest Glen, Chicago     Indian Restaurant   
57           Belmont Cragin, Chicago    Mexican Restaurant   
58                  Hermosa, Chicago          Optical Shop   
64       West Garfield Park, Chicago  Fast Food Restaurant   
65       East Garfield Park, Chicago         Garden Center   
68           South Lawndale, Chicago    Mexican Restaurant   
69          Lower West Side, Chicago         Grocery Store   
78          Washington Park, Chicago  Fast Food Restaurant   
83              Avalon Park, Chicago  Fast Food Restaurant   
84            South Chicago, Chicago    Mexican Restaurant   
85                 Burnside, Chicago           Bus Station   
91             West Pullman, Chicago  Gym / Fitness Center   
94           Garfield Ridge, Chicago        Discount Store   
95           Archer Heights, Chicago    Mexican Restaurant   
96            Brighton Park, Chicago    Mexican Restaurant   
97            McKinley Park, Chicago                 Diner   
100             West Elsdon, Chicago    Mexican Restaurant   
101               Gage Park, Chicago     Convenience Store   
102                Clearing, Chicago            Restaurant   
103               West Lawn, Chicago    Mexican Restaurant   
104            Chicago Lawn, Chicago           Pizza Place   
105          West Englewood, Chicago  Fast Food Restaurant   
106               Englewood, Chicago          Liquor Store   
107  Greater Grand Crossing, Chicago     Currency Exchange   
112             Morgan Park, Chicago             BBQ Joint   

          2nd Most Common Venue          3rd Most Common Venue  \
7                        Bakery                Thai Restaurant   
40                  Pizza Place             Chinese Restaurant   
51         Fast Food Restaurant                    Golf Course   
57                   Restaurant                     Laundromat   
58               Discount Store                           Park   
64               Clothing Store            Fried Chicken Joint   
65                   Public Art                 Discount Store   
68               Ice Cream Shop                  Grocery Store   
69           Mexican Restaurant                           Food   
78            Convenience Store                    Art Gallery   
83                 Burger Joint                            ATM   
84                Grocery Store              Convenience Store   
85                 Intersection                  Train Station   
91                   Sports Bar                            Bar   
94   Construction & Landscaping  Paper / Office Supplies Store   
95            Mobile Phone Shop                  Grocery Store   
96                  Pizza Place                  Grocery Store   
97                  Video Store             Mexican Restaurant   
100                         Bar                 Ice Cream Shop   
101          Mexican Restaurant               Asian Restaurant   
102                 Video Store                     Playground   
103               Bowling Alley                 History Museum   
104         American Restaurant             Mexican Restaurant   
105              Cosmetics Shop                   Liquor Store   
106               Grocery Store                            ATM   
107         American Restaurant           Fast Food Restaurant   
112           Currency Exchange                 Shipping Store   

         4th Most Common Venue 5th Most Common Venue  6th Most Common Venue  \
7    Latin American Restaurant         Deli / Bodega             Steakhouse   
40         American Restaurant         Train Station                 Bakery   
51               Grocery Store           Coffee Shop               Pharmacy   
57              Discount Store           Gas Station     Chinese Restaurant   
58                 Art Gallery      Departm

The clustering of the neighborhoods lead to the following results:

- Cluster 0, 2, and 3 includes only Chicago neighborhoods, so for our analysis we can skip these clusters since there is no possible match.
- Cluster 1 seems to have a very diverse mix of parks, restaurants and other interesting places, but it is hard to find the one main topic that have all neighborhoods in common.
- Cluster 4 is interesting for our analysis since we have only one neighborhood in Manhattan, East Harlem, and multiples new neighborhoods to choose from. 

So, we will define Cluster 4 as our example for the remainder of the project and the goal is to find the best fit for a person moving from East Harlem, NY to Chicago.

#### 6. Pick the cluster that your old neighborhood is in and select the neighborhoods from the new city.

In [320]:
# create a new dataframe that contains only new city neighborhoods from the cluster we've picked and skip out East Harlem
df_cluster = merged_df.loc[merged_df['Cluster Labels'] == 4]
df_cluster = df_cluster[~df_cluster['Neighborhood'].str.contains('New York')].reset_index(drop=True)
df_cluster

Neighborhood   Latitude  Longitude  Cluster Labels  \
0              Rogers Park, Chicago  42.010531 -87.670748               4   
1              Forest Glen, Chicago  41.991752 -87.751674               4   
2           Belmont Cragin, Chicago  41.931698 -87.768670               4   
3                  Hermosa, Chicago  41.928643 -87.734502               4   
4       West Garfield Park, Chicago  41.880588 -87.729223               4   
5       East Garfield Park, Chicago  41.880866 -87.702833               4   
6           South Lawndale, Chicago  41.843644 -87.712554               4   
7          Lower West Side, Chicago  41.847620 -87.671774               4   
8          Washington Park, Chicago  41.792534 -87.618105               4   
9              Avalon Park, Chicago  41.745035 -87.588658               4   
10           South Chicago, Chicago  41.734587 -87.551322               4   
11                Burnside, Chicago  41.730035 -87.596714               4   
12            West Pullman, Chicago  41.675046 -87.637823               4   
13          Garfield Ridge, Chicago  41.803617 -87.745489               4   
14          Archer Heights, Chicago  41.811422 -87.726165               4   
15           Brighton Park, Chicago  41.818922 -87.698942               4   
16           McKinley Park, Chicago  41.831700 -87.673664               4   
17             West Elsdon, Chicago  41.793922 -87.724498               4   
18               Gage Park, Chicago  41.795033 -87.696164               4   
19                Clearing, Chicago  41.780588 -87.773388               4   
20               West Lawn, Chicago  41.772811 -87.722275               4   
21            Chicago Lawn, Chicago  41.775033 -87.696441               4   
22          West Englewood, Chicago  41.778089 -87.666718               4   
23               Englewood, Chicago  41.779756 -87.645884               4   
24  Greater Grand Crossing, Chicago  41.766886 -87.620845               4   
25             Morgan Park, Chicago  41.690312 -87.666716               4   

   1st Most Common Venue       2nd Most Common Venue  \
0     Mexican Restaurant                 Pizza Place   
1      Indian Restaurant        Fast Food Restaurant   
2     Mexican Restaurant                  Restaurant   
3           Optical Shop              Discount Store   
4   Fast Food Restaurant              Clothing Store   
5          Garden Center                  Public Art   
6     Mexican Restaurant              Ice Cream Shop   
7          Grocery Store          Mexican Restaurant   
8   Fast Food Restaurant           Convenience Store   
9   Fast Food Restaurant                Burger Joint   
10    Mexican Restaurant               Grocery Store   
11           Bus Station                Intersection   
12  Gym / Fitness Center                  Sports Bar   
13        Discount Store  Construction & Landscaping   
14    Mexican Restaurant           Mobile Phone Shop   
15    Mexican Restaurant                 Pizza Place   
16                 Diner                 Video Store   
17    Mexican Restaurant                         Bar   
18     Convenience Store          Mexican Restaurant   
19            Restaurant                 Video Store   
20    Mexican Restaurant               Bowling Alley   
21           Pizza Place         American Restaurant   
22  Fast Food Restaurant              Cosmetics Shop   
23          Liquor Store               Grocery Store   
24     Currency Exchange         American Restaurant   
25             BBQ Joint           Currency Exchange   

            3rd Most Common Venue      4th Most Common Venue  \
0              Chinese Restaurant        American Restaurant   
1                     Golf Course              Grocery Store   
2                      Laundromat             Discount Store   
3                            Park                Art Gallery   
4             Fried Chicken Joint                 Shoe Store   
5                  Discount Store        Ameri

In [321]:
df_cluster.shape

(26, 14)

So, the question is, which of the 26 neighborhoods should be picked by our East Harlem migrant?

### B: Scoring of neighborhoods within the new city to make a recommendation of the best places

We'll begin with some cleaning work first.

In [323]:
# clean the dataframe
df_top10 = df_cluster[['Neighborhood']]
df_top10.head()

Neighborhood
0         Rogers Park, Chicago
1         Forest Glen, Chicago
2      Belmont Cragin, Chicago
3             Hermosa, Chicago
4  West Garfield Park, Chicago

In [326]:
# drop the name Chicago
df_top10['Neighborhood'] = df_top10['Neighborhood'].map(lambda x: x.rstrip(', Chicago'))
df_top10.head()

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Neighborhood
0         Rogers Park
1         Forest Glen
2      Belmont Cragin
3              Hermos
4  West Garfield Park

#### 7. Score each of the potential new neighborhood based on socioeconomic data and define the top 10 list.


Now, we add socioeconomic data from the City of Chicago website to find the places which might be a not so good environment.

In [327]:
# we can refer to the data frame from the beginning when we started analyzing the new city
new_socioeconomic_data.head()

Community Area Number    Neighborhood  PERCENT OF HOUSING CROWDED  \
0                    1.0     Rogers Park                         7.7   
1                    2.0      West Ridge                         7.8   
2                    3.0          Uptown                         3.8   
3                    4.0  Lincoln Square                         3.4   
4                    5.0    North Center                         0.3   

   PERCENT HOUSEHOLDS BELOW POVERTY  PERCENT AGED 16+ UNEMPLOYED  \
0                              23.6                          8.7   
1                              17.2                          8.8   
2                              24.0                          8.9   
3                              10.9                          8.2   
4                               7.5                          5.2   

   PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA  \
0                                          18.2   
1                                          20.8   
2                                          11.8   
3                                          13.4   
4                                           4.5   

   PERCENT AGED UNDER 18 OR OVER 64  PER CAPITA INCOME  Hardship Index  
0                              27.5              23939            39.0  
1                              38.5              23040            46.0  
2                              22.2              35787            20.0  
3                              25.5              37524            17.0  
4                              26.2              57123             6.0

I will use the Hardship Index only as this score includes each of the indicators.

I acknowledge that the time series ends in the year of 2012, but for this assignment I will ignore this fact and assume that the data is up to date and still valid for this decision process.


In [328]:
# get the needed columns
hardship_index = new_socioeconomic_data[['Neighborhood', 'Community Area Number', 'Hardship Index']].reset_index(drop=True)
hardship_index

Neighborhood  Community Area Number  Hardship Index
0              Rogers Park                    1.0            39.0
1               West Ridge                    2.0            46.0
2                   Uptown                    3.0            20.0
3           Lincoln Square                    4.0            17.0
4             North Center                    5.0             6.0
5                Lake View                    6.0             5.0
6             Lincoln Park                    7.0             2.0
7          Near North Side                    8.0             1.0
8              Edison Park                    9.0             8.0
9             Norwood Park                   10.0            21.0
10          Jefferson Park                   11.0            25.0
11             Forest Glen                   12.0            11.0
12              North Park                   13.0            33.0
13             Albany Park                   14.0            53.0
14            Portage Park                   15.0            35.0
15             Irving Park                   16.0            34.0
16                 Dunning                   17.0            28.0
17              Montclaire                   18.0            50.0
18          Belmont Cragin                   19.0            70.0
19                 Hermosa                   20.0            71.0
20                Avondale                   21.0            42.0
21            Logan Square                   22.0            23.0
22           Humboldt park                   23.0            85.0
23               West Town                   24.0            10.0
24                  Austin                   25.0            73.0
25      West Garfield Park                   26.0            92.0
26      East Garfield Park                   27.0            83.0
27          Near West Side                   28.0            15.0
28          North Lawndale                   29.0            87.0
29          South Lawndale                   30.0            96.0
30         Lower West Side                   31.0            76.0
31                    Loop                   32.0             3.0
32         Near South Side                   33.0             7.0
33           Armour Square                   34.0            82.0
34                 Douglas                   35.0            47.0
35                 Oakland                   36.0            78.0
36             Fuller Park                   37.0            97.0
37         Grand Boulevard                   38.0            57.0
38                 Kenwood                   39.0            26.0
39         Washington Park                   40.0            88.0
40               Hyde Park                   41.0            14.0
41                Woodlawn                   42.0            58.0
42             South Shore                   43.0            55.0
43                 Chatham                   44.0            60.0
44             Avalon Park                   45.0            41.0
45           South Chicago                   46.0            75.0
46                Burnside                   47.0            79.0
47         Calumet Heights                   48.0            38.0
48                Roseland                   49.0            52.0
49                 Pullman                   50.0            51.0
50           South Deering                   51.0            65.0
51               East Side                   52.0            64.0
52            West Pullman                   53.0            62.0
53               Riverdale                   54.0            98.0
54               Hegewisch                   55.0            44.0
55          Garfield Ridge                   56.0            32.0
56          Archer Heights                   57.0            67.0
57           Brighton Park                   58.0            84.0
58           McKinley Park                   59.0            61.0
59              Bridgeport                   60.0     

In [329]:
# merge the hardship index to the cluster and sort in ascending order
df_top10 = df_top10.merge(hardship_index, on='Neighborhood')
df_top10

Neighborhood  Community Area Number  Hardship Index
0          Rogers Park                    1.0            39.0
1          Forest Glen                   12.0            11.0
2       Belmont Cragin                   19.0            70.0
3   West Garfield Park                   26.0            92.0
4   East Garfield Park                   27.0            83.0
5       South Lawndale                   30.0            96.0
6      Lower West Side                   31.0            76.0
7      Washington Park                   40.0            88.0
8          Avalon Park                   45.0            41.0
9             Burnside                   47.0            79.0
10        West Pullman                   53.0            62.0
11      Garfield Ridge                   56.0            32.0
12      Archer Heights                   57.0            67.0
13       Brighton Park                   58.0            84.0
14       McKinley Park                   59.0            61.0
15         West Elsdon                   62.0            69.0
16           Gage Park                   63.0            93.0
17           West Lawn                   65.0            56.0
18        Chicago Lawn                   66.0            80.0
19      West Englewood                   67.0            89.0
20           Englewood                   68.0            94.0
21         Morgan Park                   75.0            30.0

In [330]:
# sort neighborhoods by Hardship Index
df_top10_sorted = df_top10.sort_values(by='Hardship Index', ascending=True).reset_index(drop=True)
df_top10_sorted

Neighborhood  Community Area Number  Hardship Index
0          Forest Glen                   12.0            11.0
1          Morgan Park                   75.0            30.0
2       Garfield Ridge                   56.0            32.0
3          Rogers Park                    1.0            39.0
4          Avalon Park                   45.0            41.0
5            West Lawn                   65.0            56.0
6        McKinley Park                   59.0            61.0
7         West Pullman                   53.0            62.0
8       Archer Heights                   57.0            67.0
9          West Elsdon                   62.0            69.0
10      Belmont Cragin                   19.0            70.0
11     Lower West Side                   31.0            76.0
12            Burnside                   47.0            79.0
13        Chicago Lawn                   66.0            80.0
14  East Garfield Park                   27.0            83.0
15       Brighton Park                   58.0            84.0
16     Washington Park                   40.0            88.0
17      West Englewood                   67.0            89.0
18  West Garfield Park                   26.0            92.0
19           Gage Park                   63.0            93.0
20           Englewood                   68.0            94.0
21      South Lawndale                   30.0            96.0

In [345]:
# cut the list of the neighborhoods down to 10
df_top10 = df_top10_sorted.head(10)
df_top10

Neighborhood  Community Area Number  Hardship Index
0     Forest Glen                   12.0            11.0
1     Morgan Park                   75.0            30.0
2  Garfield Ridge                   56.0            32.0
3     Rogers Park                    1.0            39.0
4     Avalon Park                   45.0            41.0
5       West Lawn                   65.0            56.0
6   McKinley Park                   59.0            61.0
7    West Pullman                   53.0            62.0
8  Archer Heights                   57.0            67.0
9     West Elsdon                   62.0            69.0

Now we have reduced our list of potential new neighborhoods down to 10 and can go on to analyze further relevant data. From here, it looks like Forest Glen is quite a good spot to live.

#### 8. Score remaining neighborhood based on crime data and we'll get the top 5 list.


Now, we add crime data into the analysis.

In [332]:
# we can find the names of the neighborhoods in this data source
new_crime_data = pd.read_csv('Crimes_-_2001_to_present.csv')
new_crime_data.shape

C:\Users\User\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


(7100712, 22)

Let's have a look at the file.

In [333]:
new_crime_data.head()

ID Case Number                    Date                 Block  IUCR  \
0  11034701    JA366925  01/01/2001 11:00:00 AM       016XX E 86TH PL  1153   
1  11227287    JB147188  10/08/2017 03:00:00 AM    092XX S RACINE AVE  0281   
2  11227583    JB147595  03/28/2017 02:00:00 PM       026XX W 79TH ST  0620   
3  11227293    JB147230  09/09/2017 08:17:00 PM  060XX S EBERHART AVE  0810   
4  11227634    JB147599  08/26/2017 10:00:00 AM   001XX W RANDOLPH ST  0281   

          Primary Type                          Description  \
0   DECEPTIVE PRACTICE  FINANCIAL IDENTITY THEFT OVER $ 300   
1  CRIM SEXUAL ASSAULT                       NON-AGGRAVATED   
2             BURGLARY                       UNLAWFUL ENTRY   
3                THEFT                            OVER $500   
4  CRIM SEXUAL ASSAULT                       NON-AGGRAVATED   

  Location Description  Arrest  Domestic  Beat  District  Ward  \
0            RESIDENCE   False     False   412       4.0   8.0   
1            RESIDENCE   False     False  2222      22.0  21.0   
2                OTHER   False     False   835       8.0  18.0   
3            RESIDENCE   False     False   313       3.0  20.0   
4          HOTEL/MOTEL   False     False   122       1.0  42.0   

   Community Area FBI Code  X Coordinate  Y Coordinate  Year  \
0            45.0       11           NaN           NaN  2001   
1            73.0       02           NaN           NaN  2017   
2            70.0       05           NaN           NaN  2017   
3            42.0       06           NaN           NaN  2017   
4            32.0       02           NaN           NaN  2017   

               Updated On  Latitude  Longitude Location  
0  08/05/2017 03:50:08 PM       NaN        NaN      NaN  
1  02/11/2018 03:57:41 PM       NaN        NaN      NaN  
2  02/11/2018 03:57:41 PM       NaN        NaN      NaN  
3  02/11/2018 03:57:41 PM       NaN        NaN      NaN  
4  02/11/2018 03:57:41 PM       NaN        NaN      NaN

In [334]:
# drop NaN
new_crime_data.dropna(inplace=True)
print(new_crime_data.shape)
new_crime_data.head()

(6421539, 22)


ID Case Number                    Date  \
63316  11665567    JC234307  04/10/2019 04:37:00 PM   
63401  11667963    JC235212  04/12/2019 04:08:00 PM   
63402  11667968    JC237058  04/19/2019 01:57:00 PM   
63478  11668309    JC238187  04/25/2019 05:20:00 PM   
63883  11692179    JC261724  05/13/2019 05:26:00 PM   

                                     Block  IUCR                Primary Type  \
63316                   102XX S VERNON AVE  1562                 SEX OFFENSE   
63401                   032XX N KEELER AVE  1754  OFFENSE INVOLVING CHILDREN   
63402                  002XX N LARAMIE AVE  1752  OFFENSE INVOLVING CHILDREN   
63478  108XX S DR MARTIN LUTHER KING JR DR  0486                     BATTERY   
63883                   090XX S RACINE AVE  0560                     ASSAULT   

                                             Description  \
63316                          AGG CRIMINAL SEXUAL ABUSE   
63401                     AGG SEX ASSLT OF CHILD FAM MBR   
63402  AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER   
63478                            DOMESTIC BATTERY SIMPLE   
63883                                             SIMPLE   

           Location Description  Arrest  Domestic  Beat  District  Ward  \
63316  SCHOOL, PUBLIC, BUILDING   False     False   511       5.0   9.0   
63401                 RESIDENCE   False      True  1731      17.0  30.0   
63402                 RESIDENCE   False      True  1532      15.0  28.0   
63478                 RESIDENCE   False      True   513       5.0   9.0   
63883                    STREET   False     False  2222      22.0  21.0   

       Community Area FBI Code  X Coordinate  Y Coordinate  Year  \
63316            49.0       17     1181051.0     1837225.0  2019   
63401            16.0       02     1147835.0     1921408.0  2019   
63402            25.0       17     1141669.0     1901165.0  2019   
63478            49.0      08B     1180832.0     1833222.0  2019   
63883            73.0      08A     1169908.0     1844927.0  2019   

                   Updated On   Latitude  Longitude  \
63316  08/03/2019 04:02:13 PM  41.708589 -87.612583   
63401  10/02/2019 04:13:24 PM  41.940298 -87.732066   
63402  03/18/2020 03:52:17 PM  41.884865 -87.755230   
63478  06/30/2019 03:56:27 PM  41.697609 -87.613508   
63883  06/30/2019 03:56:27 PM  41.729973 -87.653167   

                            Location  
63316     (41.708589, -87.612583094)  
63401  (41.940297617, -87.732066473)  
63402  (41.884865037, -87.755230327)  
63478  (41.697609261, -87.613507612)  
63883  (41.729973132, -87.653166753)

This file is quite huge, so we need to trim is to make it more manageable. For this, we will drop the years before 2015.

In [335]:
# Select years we want to drop
YearsToDrop = new_crime_data[ new_crime_data['Year'] < 2015 ].index

# Delete these row indexes from dataFrame
new_crime_data.drop(YearsToDrop , inplace=True)
new_crime_data.tail(50)

ID Case Number                    Date  \
7100658   9999943    HY189919  03/18/2015 08:15:00 PM   
7100659   9999944    HY182162  03/10/2015 10:05:00 PM   
7100660   9999945    HY189912  03/18/2015 04:45:00 PM   
7100661   9999946    HY189905  03/18/2015 07:40:00 PM   
7100662   9999947    HY189876  03/18/2015 07:15:00 PM   
7100663   9999948    HY189884  03/18/2015 07:50:00 PM   
7100664   9999949    HY189799  03/18/2015 06:21:00 PM   
7100665   9999950    HY189920  03/18/2015 08:32:00 PM   
7100666   9999951    HY189917  03/18/2015 07:35:00 PM   
7100667   9999952    HY189880  03/18/2015 07:45:00 PM   
7100668   9999953    HY189822  03/18/2015 07:07:00 PM   
7100669   9999954    HY189914  03/18/2015 07:51:00 PM   
7100670   9999955    HY189927  03/18/2015 08:25:00 PM   
7100671   9999956    HY189896  03/18/2015 07:00:00 PM   
7100672   9999957    HY189879  03/18/2015 07:40:00 PM   
7100673   9999958    HY189873  03/17/2015 07:00:00 AM   
7100674   9999959    HY189949  03/18/2015 09:00:00 AM   
7100675   9999960    HY189806  03/18/2015 05:40:00 PM   
7100676   9999961    HY188731  03/17/2015 07:40:00 PM   
7100677   9999962    HY189930  03/18/2015 07:00:00 AM   
7100678   9999964    HY189963  03/17/2015 09:30:00 PM   
7100679   9999967    HY189734  03/18/2015 08:57:00 AM   
7100680   9999968    HY189827  02/19/2015 08:30:00 PM   
7100681   9999969    HY189942  03/18/2015 08:30:00 PM   
7100682   9999970    HY189243  03/18/2015 09:45:00 AM   
7100683   9999971    HY189684  02/08/2015 02:00:00 PM   
7100684   9999972    HY189910  03/18/2015 07:30:00 PM   
7100685   9999973    HY189775  03/18/2015 05:15:00 PM   
7100687   9999975    HY189744  03/18/2015 03:00:00 PM   
7100688   9999976    HY189655  03/18/2015 08:00:00 AM   
7100689   9999977    HY189948  03/18/2015 08:20:00 PM   
7100690   9999978    HY189636  03/18/2015 12:00:00 PM   
7100691   9999980    HY189855  03/18/2015 07:25:00 PM   
7100692   9999981    HY189892  03/18/2015 07:26:00 PM   
7100693   9999984    HY189857  03/18/2015 07:42:00 PM   
7100694   9999985    HY189757  03/18/2015 02:00:00 PM   
7100695   9999986    HY189728  03/18/2015 05:49:00 PM   
7100696   9999988    HY189931  03/18/2015 08:25:00 PM   
7100697   9999989    HY189492  03/18/2015 03:05:00 PM   
7100698   9999990    HY189960  03/17/2015 08:00:00 PM   
7100699   9999991    HY189924  03/18/2015 08:32:00 PM   
7100700   9999992    HY189647  03/18/2015 04:55:00 PM   
7100701   9999996    HY188806  03/17/2015 11:15:00 PM   
7100702   9999997    HY189887  03/18/2015 07:55:00 PM   
7100703   9999998    HY188874  03/18/2015 04:00:00 AM   
7100704   9999999    HY189683  03/18/2015 05:08:00 PM   
7100705  11700037    JC278815  05/26/2019 12:10:00 AM   
7100707  11700926    JC279725  05/26/2019 05:13:00 PM   
7100708     24560    JC279072  05/26/2019 06:48:00 AM   
7100709     24559    JC278908  05/26/2019 02:11:00 AM   

                             Block  IUCR                Primary Type  \
7100658  035XX S COTTAGE GROVE AVE  2820               OTHER OFFENSE   
7100659         001XX N KEDZIE AVE  2890      PUBLIC PEACE VIOLATION   
7100660         028XX S FARRELL ST  0810                       THEFT   
7100661     024XX S CALIFORNIA AVE  1811                   NARCOTICS   
7100662       055XX S MICHIGAN AVE  1812                   NARCOTICS   
7100663       013XX W CULLERTON ST  4310               OTHER OFFENSE   
7100664        069XX S INDIANA AVE  143A           WEAPONS VIOLATION   
7100665           005XX E 115TH ST  1811                   NARCOTICS   
7100666  070XX S SOUTH CHICAGO AVE  5002               OTHER OFFENSE   
7100667           001XX N STATE ST  0860                       THEFT   
7100668          076XX S ESSEX AVE  143A           WEAPONS VIOLATION   
7100669            044XX W IOWA ST  1811                   NARCOTICS   
7100670            011XX W 63RD ST  2028                   NARCOTICS   
7100671        070XX S CHAPPEL AVE  0560                     ASSAULT   
7100672        014XX N HARD

In [336]:
new_crime_data.shape

(1361345, 22)

We have still over 1 million rows left in this dataframe and a wealth of information to dig into. For the purpose of this project, I will concentrate on the number of incidents only and do not take the type of crime into account.

In [337]:
# group crimes by neighborhoods and apply count() function 

df_neigh_counts = new_crime_data['Community Area'].value_counts().to_frame()
df_neigh_counts.reset_index(drop=False, inplace=True)
df_neigh_counts.rename(columns={'index':'Community Area', 'Community Area':'Count'}, inplace=True)
df_neigh_counts

Community Area  Count
0             25.0  81565
1              8.0  58702
2             32.0  49484
3             28.0  46213
4             29.0  45586
5             43.0  44720
6             23.0  41476
7             71.0  39096
8             24.0  38733
9             67.0  35923
10            49.0  34990
11            69.0  34102
12            44.0  33064
13            68.0  32528
14            66.0  29946
15            26.0  29898
16             6.0  29717
17            22.0  25677
18            27.0  25419
19            61.0  23692
20            19.0  23602
21            46.0  23577
22            30.0  23372
23             7.0  22131
24            53.0  20513
25             1.0  19768
26            42.0  18693
27             3.0  18063
28             2.0  17458
29            38.0  16949
30            15.0  16587
31            73.0  16262
32            16.0  14701
33            40.0  13688
34            35.0  13556
35            31.0  12894
36            77.0  12839
37            70.0  12614
38            14.0  12398
39            58.0  12370
40            63.0  11599
41            21.0  11584
42            75.0  10459
43            56.0  10015
44            65.0   9817
45             4.0   9721
46            33.0   9616
47            51.0   9503
48            41.0   8816
49            76.0   8415
50            17.0   7959
51            60.0   7950
52            20.0   7712
53            48.0   7256
54            39.0   7256
55             5.0   6929
56            54.0   6756
57            45.0   6670
58            52.0   6128
59            10.0   6080
60            50.0   5891
61            11.0   5490
62            34.0   5300
63            62.0   5223
64            59.0   5032
65            64.0   4813
66            72.0   4811
67            13.0   4690
68            37.0   4546
69            57.0   4470
70            36.0   3344
71            18.0   3102
72            55.0   2978
73            74.0   2898
74            12.0   2584
75            47.0   1984
76             9.0   1382

After having count the total numbers of crimes over the time period 2015 - March 2020, I will calculate the average crime count per year as a rough indication for how dangerous a neighborhood was in the past. 

In [338]:
# count per year - divided by 4.25 (four full years and a quarter of 2020)
df_neigh_counts['Count per Year'] = df_neigh_counts['Count'] / 4.25 
df_neigh_counts

Community Area  Count  Count per Year
0             25.0  81565    19191.764706
1              8.0  58702    13812.235294
2             32.0  49484    11643.294118
3             28.0  46213    10873.647059
4             29.0  45586    10726.117647
5             43.0  44720    10522.352941
6             23.0  41476     9759.058824
7             71.0  39096     9199.058824
8             24.0  38733     9113.647059
9             67.0  35923     8452.470588
10            49.0  34990     8232.941176
11            69.0  34102     8024.000000
12            44.0  33064     7779.764706
13            68.0  32528     7653.647059
14            66.0  29946     7046.117647
15            26.0  29898     7034.823529
16             6.0  29717     6992.235294
17            22.0  25677     6041.647059
18            27.0  25419     5980.941176
19            61.0  23692     5574.588235
20            19.0  23602     5553.411765
21            46.0  23577     5547.529412
22            30.0  23372     5499.294118
23             7.0  22131     5207.294118
24            53.0  20513     4826.588235
25             1.0  19768     4651.294118
26            42.0  18693     4398.352941
27             3.0  18063     4250.117647
28             2.0  17458     4107.764706
29            38.0  16949     3988.000000
30            15.0  16587     3902.823529
31            73.0  16262     3826.352941
32            16.0  14701     3459.058824
33            40.0  13688     3220.705882
34            35.0  13556     3189.647059
35            31.0  12894     3033.882353
36            77.0  12839     3020.941176
37            70.0  12614     2968.000000
38            14.0  12398     2917.176471
39            58.0  12370     2910.588235
40            63.0  11599     2729.176471
41            21.0  11584     2725.647059
42            75.0  10459     2460.941176
43            56.0  10015     2356.470588
44            65.0   9817     2309.882353
45             4.0   9721     2287.294118
46            33.0   9616     2262.588235
47            51.0   9503     2236.000000
48            41.0   8816     2074.352941
49            76.0   8415     1980.000000
50            17.0   7959     1872.705882
51            60.0   7950     1870.588235
52            20.0   7712     1814.588235
53            48.0   7256     1707.294118
54            39.0   7256     1707.294118
55             5.0   6929     1630.352941
56            54.0   6756     1589.647059
57            45.0   6670     1569.411765
58            52.0   6128     1441.882353
59            10.0   6080     1430.588235
60            50.0   5891     1386.117647
61            11.0   5490     1291.764706
62            34.0   5300     1247.058824
63            62.0   5223     1228.941176
64            59.0   5032     1184.000000
65            64.0   4813     1132.470588
66            72.0   4811     1132.000000
67            13.0   4690     1103.529412
68            37.0   4546     1069.647059
69            57.0   4470     1051.764706
70            36.0   3344      786.823529
71            18.0   3102      729.882353
72            55.0   2978      700.705882
73            74.0   2898      681.882353
74            12.0   2584      608.000000
75            47.0   1984      466.823529
76             9.0   1382      325.176471

In [339]:
# rename column so the match between dataframes
df_neigh_counts.rename(columns={'Community Area': 'Community Area Number'}, inplace=True)
df_neigh_counts

Community Area Number  Count  Count per Year
0                    25.0  81565    19191.764706
1                     8.0  58702    13812.235294
2                    32.0  49484    11643.294118
3                    28.0  46213    10873.647059
4                    29.0  45586    10726.117647
5                    43.0  44720    10522.352941
6                    23.0  41476     9759.058824
7                    71.0  39096     9199.058824
8                    24.0  38733     9113.647059
9                    67.0  35923     8452.470588
10                   49.0  34990     8232.941176
11                   69.0  34102     8024.000000
12                   44.0  33064     7779.764706
13                   68.0  32528     7653.647059
14                   66.0  29946     7046.117647
15                   26.0  29898     7034.823529
16                    6.0  29717     6992.235294
17                   22.0  25677     6041.647059
18                   27.0  25419     5980.941176
19                   61.0  23692     5574.588235
20                   19.0  23602     5553.411765
21                   46.0  23577     5547.529412
22                   30.0  23372     5499.294118
23                    7.0  22131     5207.294118
24                   53.0  20513     4826.588235
25                    1.0  19768     4651.294118
26                   42.0  18693     4398.352941
27                    3.0  18063     4250.117647
28                    2.0  17458     4107.764706
29                   38.0  16949     3988.000000
30                   15.0  16587     3902.823529
31                   73.0  16262     3826.352941
32                   16.0  14701     3459.058824
33                   40.0  13688     3220.705882
34                   35.0  13556     3189.647059
35                   31.0  12894     3033.882353
36                   77.0  12839     3020.941176
37                   70.0  12614     2968.000000
38                   14.0  12398     2917.176471
39                   58.0  12370     2910.588235
40                   63.0  11599     2729.176471
41                   21.0  11584     2725.647059
42                   75.0  10459     2460.941176
43                   56.0  10015     2356.470588
44                   65.0   9817     2309.882353
45                    4.0   9721     2287.294118
46                   33.0   9616     2262.588235
47                   51.0   9503     2236.000000
48                   41.0   8816     2074.352941
49                   76.0   8415     1980.000000
50                   17.0   7959     1872.705882
51                   60.0   7950     1870.588235
52                   20.0   7712     1814.588235
53                   48.0   7256     1707.294118
54                   39.0   7256     1707.294118
55                    5.0   6929     1630.352941
56                   54.0   6756     1589.647059
57                   45.0   6670     1569.411765
58                   52.0   6128     1441.882353
59                   10.0   6080     1430.588235
60                   50.0   5891     1386.117647
61                   11.0   5490     1291.764706
62                   34.0   5300     1247.058824
63                   62.0   5223     1228.941176
64                   59.0   5032     1184.000000
65                   64.0   4813     1132.470588
66                   72.0   4811     1132.000000
67                   13.0   4690     1103.529412
68                   37.0   4546     1069.647059
69                   57.0   4470     1051.764706
70                   36.0   3344      786.823529
71                   18.0   3102      729.882353
72                   55.0   2978      700.705882
73                   74.0   2898      681.882353
74                   12.0   2584      608.000000
75                   47.0   1984      466.823529
76                    9.0   1382      325.176471

In [346]:
# merge crimes per year to top10 list
df_top5 = df_top10.merge(df_neigh_counts, on='Community Area Number')
df_top5

Neighborhood  Community Area Number  Hardship Index  Count  \
0     Forest Glen                   12.0            11.0   2584   
1     Morgan Park                   75.0            30.0  10459   
2  Garfield Ridge                   56.0            32.0  10015   
3     Rogers Park                    1.0            39.0  19768   
4     Avalon Park                   45.0            41.0   6670   
5       West Lawn                   65.0            56.0   9817   
6   McKinley Park                   59.0            61.0   5032   
7    West Pullman                   53.0            62.0  20513   
8  Archer Heights                   57.0            67.0   4470   
9     West Elsdon                   62.0            69.0   5223   

   Count per Year  
0      608.000000  
1     2460.941176  
2     2356.470588  
3     4651.294118  
4     1569.411765  
5     2309.882353  
6     1184.000000  
7     4826.588235  
8     1051.764706  
9     1228.941176

In [347]:
# sort in ascending order of count per year
df_top5 = df_top5.sort_values(by='Count per Year', ascending=True).reset_index(drop=True)
df_top5

Neighborhood  Community Area Number  Hardship Index  Count  \
0     Forest Glen                   12.0            11.0   2584   
1  Archer Heights                   57.0            67.0   4470   
2   McKinley Park                   59.0            61.0   5032   
3     West Elsdon                   62.0            69.0   5223   
4     Avalon Park                   45.0            41.0   6670   
5       West Lawn                   65.0            56.0   9817   
6  Garfield Ridge                   56.0            32.0  10015   
7     Morgan Park                   75.0            30.0  10459   
8     Rogers Park                    1.0            39.0  19768   
9    West Pullman                   53.0            62.0  20513   

   Count per Year  
0      608.000000  
1     1051.764706  
2     1184.000000  
3     1228.941176  
4     1569.411765  
5     2309.882353  
6     2356.470588  
7     2460.941176  
8     4651.294118  
9     4826.588235

Again, Forest Glen has the best score in relation to the crime statistics which should come at no surprise. Interestingly, however, is that neighborhoods with a high Hardship Index seem to have relatively low crime rates.  

In [348]:
# cut the list of the neighborhoods down to 5
df_top5 = df_top5.head(5)
df_top5

Neighborhood  Community Area Number  Hardship Index  Count  \
0     Forest Glen                   12.0            11.0   2584   
1  Archer Heights                   57.0            67.0   4470   
2   McKinley Park                   59.0            61.0   5032   
3     West Elsdon                   62.0            69.0   5223   
4     Avalon Park                   45.0            41.0   6670   

   Count per Year  
0      608.000000  
1     1051.764706  
2     1184.000000  
3     1228.941176  
4     1569.411765

#### 9. Last step is to check housing prices for the top 5 list and decide based on financial resources available.

In [349]:
# load the housing prices from file
housing_data = pd.read_csv('Neighborhood_Zhvi_AllHomes.csv')
housing_data.head()

RegionID         RegionName         City State  \
0    274772   Northeast Dallas       Dallas    TX   
1    112345           Maryvale      Phoenix    AZ   
2    192689           Paradise    Las Vegas    NV   
3    270958    Upper West Side     New York    NY   
4    118208  South Los Angeles  Los Angeles    CA   

                            Metro          CountyName  SizeRank   1996-04  \
0     Dallas-Fort Worth-Arlington       Dallas County         1  135166.0   
1         Phoenix-Mesa-Scottsdale     Maricopa County         2       NaN   
2    Las Vegas-Henderson-Paradise        Clark County         3  140161.0   
3     New York-Newark-Jersey City     New York County         4  245906.0   
4  Los Angeles-Long Beach-Anaheim  Los Angeles County         5  133824.0   

    1996-05   1996-06   1996-07   1996-08   1996-09   1996-10   1996-11  \
0  135884.0  136017.0  135645.0  135449.0  135255.0  135714.0  135654.0   
1       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2  140431.0  140572.0  140837.0  141260.0  141735.0  142145.0  142316.0   
3  246768.0  247673.0  247748.0  247878.0  247972.0  248829.0  249759.0   
4  134281.0  134569.0  134741.0  134761.0  134855.0  134823.0  134772.0   

    1996-12   1997-01   1997-02   1997-03   1997-04   1997-05   1997-06  \
0  135743.0  135809.0  136179.0  135807.0  135537.0  135153.0  135666.0   
1       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2  142629.0  142901.0  143374.0  143602.0  144100.0  144378.0  144656.0   
3  250912.0  252215.0  254551.0  256782.0  258286.0  260071.0  261957.0   
4  134620.0  133993.0  133537.0  133180.0  133258.0  133094.0  133177.0   

    1997-07   1997-08   1997-09   1997-10   1997-11   1997-12   1998-01  \
0  136707.0  137646.0  138308.0  138409.0  139021.0  139684.0  139676.0   
1       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2  144747.0  144664.0  144748.0  144949.0  145489.0  145953.0  146638.0   
3  265261.0  268195.0  271712.0  274070.0  277397.0  280839.0  284753.0   
4  133641.0  134399.0  134998.0  135590.0  136086.0  136852.0  138153.0   

    1998-02   1998-03   1998-04   1998-05   1998-06   1998-07   1998-08  \
0  139397.0  139228.0  139367.0  139527.0  139401.0  139564.0  139515.0   
1       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2  147260.0  147925.0  148188.0  148379.0  148853.0  149190.0  149580.0   
3  287557.0  290351.0  293226.0  295641.0  298423.0  301059.0  304851.0   
4  139713.0  140942.0  141315.0  141543.0  141608.0  141169.0  140826.0   

    1998-09   1998-10   1998-11   1998-12   1999-01   1999-02   1999-03  \
0  140066.0  139883.0  140039.0  139668.0  140691.0  141986.0  143601.0   
1       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2  149623.0  149820.0  149993.0  150059.0  149890.0  149718.0  149749.0   
3  307884.0  312043.0  314914.0  317937.0  320018.0  322526.0  325199.0   
4  140771.0  141151.0  141619.0  141891.0  142393.0  142738.0  143293.0   

    1999-04   1999-05   1999-06   1999-07   1999-08   1999-09   1999-10  \
0  144744.0  145735.0  146837.0  147702.0  148431.0  148699.0  149458.0   
1       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2  150031.0  150491.0  151105.0  152291.0  153278.0  154246.0  154823.0   
3  327798.0  330740.0  333673.0  337746.0  342064.0  347639.0  352029.0   
4  143767.0  144334.0  145245.0  146545.0  147362.0  147871.0  148234.0   

    1999-11   1999-12   2000-01   2000-02   2000-03   2000-04   2000-05  \
0  150030.0  150848.0  151127.0  151654.0  151851.0  152110.0  152178.0   
1       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2  155549.0  156202.0  156869.0  157378.0  157962.0  158666.0  159392.0   
3  355917.0  358641.0  361958.0  366811.0  371884.0  378554.0  385621.0   
4  148966.0  149685.0  150360.0  150848.0  151408.0  152087.0  153004.0   

    2000-06   2000-07   2000-08   2000-09   2000-10   2000-11   

In [350]:
# drop all neighorhoods with NaN
housing_data.dropna(inplace=True)

# clean the table by filtering only for city of Chicago
housing_data = housing_data[housing_data['City'].str.contains('Chicago')]
housing_data.head()

RegionID        RegionName     City State                     Metro  \
51     269592      Logan Square  Chicago    IL  Chicago-Naperville-Elgin   
103    403169  West Rogers Park  Chicago    IL  Chicago-Naperville-Elgin   
150    269566       Albany Park  Chicago    IL  Chicago-Naperville-Elgin   
155    269609            Uptown  Chicago    IL  Chicago-Naperville-Elgin   
159    269589         Lake View  Chicago    IL  Chicago-Naperville-Elgin   

      CountyName  SizeRank   1996-04   1996-05   1996-06   1996-07   1996-08  \
51   Cook County        52  141259.0  141514.0  141951.0  142616.0  143719.0   
103  Cook County       104  134485.0  134536.0  134817.0  134843.0  135215.0   
150  Cook County       151  125085.0  125047.0  124995.0  124285.0  124306.0   
155  Cook County       156  117334.0  117428.0  117918.0  118280.0  119152.0   
159  Cook County       160  219878.0  220418.0  221375.0  221533.0  222385.0   

      1996-09   1996-10   1996-11   1996-12   1997-01   1997-02   1997-03  \
51   144590.0  144948.0  145248.0  145602.0  146852.0  148034.0  148809.0   
103  135967.0  136911.0  138087.0  139057.0  139868.0  140404.0  141007.0   
150  124571.0  125658.0  126910.0  128310.0  129572.0  130721.0  131425.0   
155  120073.0  121043.0  122065.0  122938.0  123857.0  124751.0  125863.0   
159  223906.0  225952.0  228001.0  229617.0  231756.0  233679.0  236259.0   

      1997-04   1997-05   1997-06   1997-07   1997-08   1997-09   1997-10  \
51   148508.0  149142.0  149668.0  150311.0  149586.0  148804.0  147830.0   
103  141110.0  141897.0  142254.0  142839.0  142065.0  140488.0  138303.0   
150  131362.0  131904.0  132600.0  133975.0  134308.0  133644.0  131797.0   
155  126282.0  127107.0  127161.0  127341.0  126442.0  125661.0  124896.0   
159  236956.0  238443.0  238872.0  240308.0  240341.0  239316.0  237330.0   

      1997-11   1997-12   1998-01   1998-02   1998-03   1998-04   1998-05  \
51   147206.0  146804.0  145950.0  145373.0  145459.0  147118.0  148435.0   
103  136224.0  134878.0  134318.0  134250.0  134673.0  134975.0  135044.0   
150  129868.0  128535.0  127623.0  127074.0  127245.0  127583.0  128696.0   
155  124558.0  124799.0  125487.0  126419.0  127633.0  129120.0  130466.0   
159  235693.0  235601.0  235458.0  236170.0  236923.0  238793.0  240177.0   

      1998-06   1998-07   1998-08   1998-09   1998-10   1998-11   1998-12  \
51   149327.0  149489.0  151244.0  154021.0  158735.0  162962.0  166705.0   
103  135032.0  135372.0  137427.0  140308.0  144023.0  147079.0  149531.0   
150  129467.0  130890.0  132389.0  135400.0  138547.0  141602.0  143377.0   
155  132066.0  133930.0  136757.0  139709.0  142868.0  145343.0  147461.0   
159  242445.0  245266.0  249220.0  253834.0  259330.0  264570.0  268659.0   

      1999-01   1999-02   1999-03   1999-04   1999-05   1999-06   1999-07  \
51   168883.0  170759.0  172089.0  173533.0  174824.0  177015.0  179488.0   
103  150825.0  151912.0  152728.0  154084.0  155426.0  157771.0  159887.0   
150  145038.0  146656.0  148034.0  149534.0  150244.0  151834.0  153148.0   
155  148715.0  150219.0  151406.0  153039.0  154670.0  157188.0  159966.0   
159  271583.0  273950.0  276200.0  278870.0  281770.0  285344.0  289013.0   

      1999-08   1999-09   1999-10   1999-11   1999-12   2000-01   2000-02  \
51   181100.0  181882.0  181938.0  182710.0  184024.0  186622.0  189531.0   
103  161266.0  161932.0  162382.0  163618.0  165163.0  167815.0  170331.0   
150  154754.0  155438.0  156303.0  157540.0  159572.0  161925.0  164140.0   
155  162388.0  164358.0  166264.0  168635.0  171034.0  174014.0  176745.0   
159  292278.0  295248.0  298041.0  301292.0  304510.0  308931.0  313559.0   

      2000-03   2000-04   2000-05   2000-06   2000-07   2000-08   2000-09  \
51   192911.0  195622.0  198459.0  201137.0  204388.0  207591.0  210796.0   
103  172869.0  174882.0  177141.0  179011.0  181257.0  183438.0  185864.0   
150  166452.0  169049.0  171858.0  174685.0  177241.0  179

In [351]:
# let's take only the current date into account
housing_data = housing_data[['RegionName', '2020-02']].reset_index(drop=True)

# Rename column "RegionName" which is exactly the same as "Neighborhood"
housing_data.rename(columns={'RegionName': 'Neighborhood'}, inplace=True)

housing_data.head()

Neighborhood  2020-02
0      Logan Square   398122
1  West Rogers Park   303728
2       Albany Park   315109
3            Uptown   300138
4         Lake View   533551

In [352]:
# merge housing prices to top3 list and sort in ascending order
df_top3 = df_top5.merge(housing_data, on='Neighborhood')
df_top3

Neighborhood  Community Area Number  Hardship Index  Count  \
0     Forest Glen                   12.0            11.0   2584   
1  Archer Heights                   57.0            67.0   4470   
2   McKinley Park                   59.0            61.0   5032   
3     West Elsdon                   62.0            69.0   5223   
4     Avalon Park                   45.0            41.0   6670   

   Count per Year  2020-02  
0      608.000000   363921  
1     1051.764706   213038  
2     1184.000000   235814  
3     1228.941176   203498  
4     1569.411765   122019

In [353]:
# clean dataframe
df_top3 = df_top3[['Neighborhood', 'Hardship Index', 'Count per Year', '2020-02']].reset_index(drop=True)
# Rename columns
df_top3.rename(columns={'Count per Year': 'Crimes per Year', '2020-02': 'Current avg. Housing Prices'}, inplace=True)
df_top3

Neighborhood  Hardship Index  Crimes per Year  \
0     Forest Glen            11.0       608.000000   
1  Archer Heights            67.0      1051.764706   
2   McKinley Park            61.0      1184.000000   
3     West Elsdon            69.0      1228.941176   
4     Avalon Park            41.0      1569.411765   

   Current avg. Housing Prices  
0                       363921  
1                       213038  
2                       235814  
3                       203498  
4                       122019

## Results and Discussion <a name="results"></a>

Finally, the last step in my analysis shows a high relationship between socioeconomic data, crime data and the average housing prices for Forest Glen. 

__The final decision for a new neighborhood can now be based on the financial resources available. If a budget of more than USD 360k is not a problem, than Forest Glen would be the best fit for someone moving from East Harlem, NY to Chicago.__